// a16z portfolio batch — net-new entries to add as targeting (May 4 2026)
// Health/bio, defense, NFT/gaming-crypto, mega-public, defunct/struggling all filtered out.
// Each entry includes "(a16z)" suffix.

import type { EntryType, Domain } from "./types";

export interface NextBatchSeed {
  finalName: string;
  renameFrom?: string;
  type: EntryType;
  domain: Domain;
  note?: string;
}

export const A16Z_BATCH_2026_05_04: NextBatchSeed[] = [
  { finalName: "11x (a16z)", type: "company", domain: "frontier-ai" },
  { finalName: "Addi (a16z)", type: "company", domain: "fintech" },
  { finalName: "AirGarage (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Airbase (a16z)", type: "company", domain: "fintech" },
  { finalName: "Alluxio (a16z)", type: "company", domain: "infra-devtools" },
  { finalName: "AltSchool (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Alta (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Amca (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Angle (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "AnyRoad (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Arc (a16z)", type: "company", domain: "infra-devtools" },
  { finalName: "Arcjet (a16z)", type: "company", domain: "infra-devtools" },
  { finalName: "Atlys (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Autograph.io (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Axoni (a16z)", type: "company", domain: "fintech" },
  { finalName: "Azra Games (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Backflip AI (a16z)", type: "company", domain: "frontier-ai" },
  { finalName: "Beeps (a16z)", type: "company", domain: "frontier-ai" },
  { finalName: "Believer (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Belong (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "BigScreen (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Black Ore Technologies (a16z)", type: "company", domain: "infra-devtools" },
  { finalName: "Bold (a16z)", type: "company", domain: "fintech" },
  { finalName: "Bonfire Studios (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Bounce (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Braid.ai (a16z)", type: "company", domain: "frontier-ai" },
  { finalName: "Branch International (a16z)", type: "company", domain: "fintech" },
  { finalName: "Braveheart (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Brightside (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "CCP Games (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "CHIP Professionals (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "CYGNVS (a16z)", type: "company", domain: "infra-devtools" },
  { finalName: "California Forever (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Camber (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Camu (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Capitolis (a16z)", type: "company", domain: "fintech" },
  { finalName: "Capriza (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Carbonated (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Carry1st (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Charthop (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Cider (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Civitai (a16z)", type: "company", domain: "frontier-ai" },
  { finalName: "Clerk (a16z)", type: "company", domain: "infra-devtools" },
  { finalName: "Clipboard (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Clover Network (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Cluely (a16z)", type: "company", domain: "frontier-ai" },
  { finalName: "Clutch (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Co:Create (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Coactive (a16z)", type: "company", domain: "frontier-ai" },
  { finalName: "CodeCombat (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Codi (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Comma (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Command Zero (a16z)", type: "company", domain: "infra-devtools" },
  { finalName: "Compound (a16z)", type: "company", domain: "fintech" },
  { finalName: "Concourse (a16z)", type: "company", domain: "infra-devtools" },
  { finalName: "Core Loop (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Cotool (a16z)", type: "company", domain: "frontier-ai" },
  { finalName: "Crossbeam (a16z)", type: "company", domain: "infra-devtools" },
  { finalName: "Crux (a16z)", type: "company", domain: "infra-devtools" },
  { finalName: "Cuenca (a16z)", type: "company", domain: "fintech" },
  { finalName: "Cult of the North (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Culture Wireless (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Current (a16z)", type: "company", domain: "fintech" },
  { finalName: "Cyngn (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Datanomik (a16z)", type: "company", domain: "fintech" },
  { finalName: "Deeptune (a16z)", type: "company", domain: "frontier-ai" },
  { finalName: "Diode (a16z)", type: "company", domain: "infra-devtools" },
  { finalName: "Dispatch (a16z)", type: "company", domain: "infra-devtools" },
  { finalName: "Distributional (a16z)", type: "company", domain: "frontier-ai" },
  { finalName: "District (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Divvy Homes (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Doxel (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Dwolla (a16z)", type: "company", domain: "fintech" },
  { finalName: "Dynamic Labs, Inc. (a16z)", type: "company", domain: "infra-devtools" },
  { finalName: "EPAL, INC. (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Earnin (a16z)", type: "company", domain: "fintech" },
  { finalName: "End Game (a16z)", type: "company", domain: "infra-devtools" },
  { finalName: "EngFlow (a16z)", type: "company", domain: "frontier-ai" },
  { finalName: "Entropy (a16z)", type: "company", domain: "infra-devtools" },
  { finalName: "Envoy (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Equal IQ (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Equals (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Espresso (Translucence Research Inc) (a16z)", type: "company", domain: "infra-devtools" },
  { finalName: "EveryRealm (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Fashivly (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Feedplan (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Filmhub (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Flash Hoops (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Flock (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Flock Homes (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Flow (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "FlyHomes (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Foodology (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Formation (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Foundation (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Freatic (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Fudo (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "FurtherAI (a16z)", type: "company", domain: "frontier-ai" },
  { finalName: "GamerXSociety (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Gamma.app (a16z)", type: "company", domain: "frontier-ai" },
  { finalName: "Gitbutler (a16z)", type: "company", domain: "infra-devtools" },
  { finalName: "Glif (a16z)", type: "company", domain: "frontier-ai" },
  { finalName: "Glimpse (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Glorify (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Glossbird (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "GoodData (a16z)", type: "company", domain: "infra-devtools" },
  { finalName: "Greenlight (a16z)", type: "company", domain: "fintech" },
  { finalName: "Greether (a16z)", type: "company", domain: "infra-devtools" },
  { finalName: "Gym Class VR (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Harbor (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Hedra (a16z)", type: "company", domain: "frontier-ai" },
  { finalName: "Here Not There, Inc. (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Hilbert (a16z)", type: "company", domain: "frontier-ai" },
  { finalName: "Hipcamp (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "IFTTT (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "IYK (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Imply (a16z)", type: "company", domain: "infra-devtools" },
  { finalName: "Incention (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Infinite Athlete (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Infinite Machine (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Instart (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Intro (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Inventa (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Irreverent Labs (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Jeeves (a16z)", type: "company", domain: "fintech" },
  { finalName: "Journera (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "KIKI (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Kadabra (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Kaedim (a16z)", type: "company", domain: "frontier-ai" },
  { finalName: "Kairos (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Kaizen Labs (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Kavak (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Keep (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Kindred (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Kinter (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Kiosk (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "KoBold Metals (a16z)", type: "company", domain: "fintech" },
  { finalName: "Kodex (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Kong (a16z)", type: "company", domain: "infra-devtools" },
  { finalName: "Kosen Labs (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Krea (a16z)", type: "company", domain: "frontier-ai" },
  { finalName: "LTSE (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Labster (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Lighter (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Lightup (a16z)", type: "company", domain: "infra-devtools" },
  { finalName: "Limitless (a16z)", type: "company", domain: "frontier-ai" },
  { finalName: "Lio (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Local Motion (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Locale (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Loft (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "LootRush (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Lumi Interactive (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "MEGA (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Macro (a16z)", type: "company", domain: "frontier-ai" },
  { finalName: "Mainframe Industries (a16z)", type: "company", domain: "frontier-ai" },
  { finalName: "Manifold (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Marker Learning (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Matik (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Mayvenn (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Mem (a16z)", type: "company", domain: "frontier-ai" },
  { finalName: "Meridian (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Merit Systems (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Meta4 Capital (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Metatheory (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Method Security (a16z)", type: "company", domain: "infra-devtools" },
  { finalName: "Mirage (a16z)", type: "company", domain: "frontier-ai" },
  { finalName: "Mirelo AI (a16z)", type: "company", domain: "frontier-ai" },
  { finalName: "ModernFi (a16z)", type: "company", domain: "fintech" },
  { finalName: "Moov (a16z)", type: "company", domain: "fintech" },
  { finalName: "Mother Computer Inc. (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Motherduck (a16z)", type: "company", domain: "infra-devtools" },
  { finalName: "Mountaintop Studios (a16z)", type: "company", domain: "frontier-ai" },
  { finalName: "Muse App Inc (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Mux (a16z)", type: "company", domain: "infra-devtools" },
  { finalName: "Mvmnt (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Mythical Games (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "NG.CASH (a16z)", type: "company", domain: "fintech" },
  { finalName: "NOD Games (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "NX (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "NationBuilder (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Neighbor (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Netography (a16z)", type: "company", domain: "infra-devtools" },
  { finalName: "Nexthop (a16z)", type: "company", domain: "infra-devtools" },
  { finalName: "Oboe (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Odyssey (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Odyssey Interactive (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "One More Game (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "OpenRouter (a16z)", type: "company", domain: "frontier-ai" },
  { finalName: "Orderful (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Original Games (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Outing (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Overtime (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Overwolf (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Palmstreet (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Paloma (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Patch (a16z)", type: "company", domain: "fintech" },
  { finalName: "Payall (a16z)", type: "company", domain: "fintech" },
  { finalName: "Payrails (a16z)", type: "company", domain: "fintech" },
  { finalName: "People.ai (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Petual (a16z)", type: "company", domain: "frontier-ai" },
  { finalName: "Phota Labs (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Pietra (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Pimlico (a16z)", type: "company", domain: "infra-devtools" },
  { finalName: "Podium Automation (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Point (a16z)", type: "company", domain: "fintech" },
  { finalName: "Poseidon (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Preset (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Prisms (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Promise (a16z)", type: "company", domain: "frontier-ai" },
  { finalName: "Proof Holdings (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Proof of Play (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Propel (a16z)", type: "company", domain: "fintech" },
  { finalName: "Protege (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Proven.com (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Pyn (a16z)", type: "company", domain: "fintech" },
  { finalName: "QuiverAI (a16z)", type: "company", domain: "frontier-ai" },
  { finalName: "Rabbit (a16z)", type: "company", domain: "frontier-ai" },
  { finalName: "Radiant (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Raid Base (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "RapidAPI (a16z)", type: "company", domain: "infra-devtools" },
  { finalName: "Rappi (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Rasa (a16z)", type: "company", domain: "frontier-ai" },
  { finalName: "Raspberry AI (a16z)", type: "company", domain: "frontier-ai" },
  { finalName: "Reface (a16z)", type: "company", domain: "frontier-ai" },
  { finalName: "Reforge (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Relay (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Replay (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Revolut (a16z)", type: "company", domain: "fintech" },
  { finalName: "Rewatch (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Rigup (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Rive (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Roboto Games (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Rollup AI (a16z)", type: "company", domain: "frontier-ai" },
  { finalName: "Run the World (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Runloop (a16z)", type: "company", domain: "infra-devtools" },
  { finalName: "Rye (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Salt AI (a16z)", type: "company", domain: "frontier-ai" },
  { finalName: "Sandbox VR (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Sardine (a16z)", type: "company", domain: "infra-devtools" },
  { finalName: "Scene Infrastructure Co (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Segura (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "SentiLink (a16z)", type: "company", domain: "infra-devtools" },
  { finalName: "Series Entertainment (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Sesame (a16z)", type: "company", domain: "frontier-ai" },
  { finalName: "Setpoint.io (a16z)", type: "company", domain: "fintech" },
  { finalName: "Sharp Performance (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Shef (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Shizuku AI (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Shop Rodeo (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Singularity 6 (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Sky (a16z)", type: "company", domain: "frontier-ai" },
  { finalName: "Sleeper (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Sloyd (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Smartcar (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Snackpass (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Socket (a16z)", type: "company", domain: "infra-devtools" },
  { finalName: "Spade (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Sphere (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "SpotOn (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Sprig (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Stacker (a16z)", type: "company", domain: "infra-devtools" },
  { finalName: "Starburst (a16z)", type: "company", domain: "infra-devtools" },
  { finalName: "Stipple Bio (a16z)", type: "company", domain: "infra-devtools" },
  { finalName: "Stoik (a16z)", type: "company", domain: "infra-devtools" },
  { finalName: "Stonks (a16z)", type: "company", domain: "fintech" },
  { finalName: "Stuut (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Super Evil MegaCorp (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Supermove (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Supersonik (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Svix (a16z)", type: "company", domain: "infra-devtools" },
  { finalName: "SwayBrand, Inc. (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Synapse (a16z)", type: "company", domain: "fintech" },
  { finalName: "Tako (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Talos (a16z)", type: "company", domain: "infra-devtools" },
  { finalName: "Tapi (a16z)", type: "company", domain: "fintech" },
  { finalName: "Teespring (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Testcode (a16z)", type: "company", domain: "infra-devtools" },
  { finalName: "Theorycraft Games (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Tigris Data (a16z)", type: "company", domain: "infra-devtools" },
  { finalName: "Timbucktoo (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Titan (a16z)", type: "company", domain: "fintech" },
  { finalName: "Toma (a16z)", type: "company", domain: "frontier-ai" },
  { finalName: "TopKey (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Treeline (a16z)", type: "company", domain: "infra-devtools" },
  { finalName: "Truffle Security (a16z)", type: "company", domain: "infra-devtools" },
  { finalName: "Ulysses (a16z)", type: "company", domain: "frontier-ai" },
  { finalName: "UnifyID (a16z)", type: "company", domain: "infra-devtools" },
  { finalName: "Unisound (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Universal (a16z)", type: "company", domain: "infra-devtools" },
  { finalName: "UpSmith (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Upstash (a16z)", type: "company", domain: "infra-devtools" },
  { finalName: "VGS (a16z)", type: "company", domain: "infra-devtools" },
  { finalName: "Vaas (a16z)", type: "company", domain: "infra-devtools" },
  { finalName: "Vantage (a16z)", type: "company", domain: "infra-devtools" },
  { finalName: "Ventrilo (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Vesta (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Viggle (a16z)", type: "company", domain: "frontier-ai" },
  { finalName: "Virch Merch (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Vitally (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Voldex (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Wabi AI (a16z)", type: "company", domain: "frontier-ai" },
  { finalName: "WaveForms AI (a16z)", type: "company", domain: "frontier-ai" },
  { finalName: "Waymark (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Wealthmore (a16z)", type: "company", domain: "fintech" },
  { finalName: "Wingspan (a16z)", type: "company", domain: "fintech" },
  { finalName: "WorkBoard (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Wrapbook (a16z)", type: "company", domain: "fintech" },
  { finalName: "XBuild (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Yuno (a16z)", type: "company", domain: "fintech" },
  { finalName: "Yupp (a16z)", type: "company", domain: "frontier-ai" },
  { finalName: "Zencoder (a16z)", type: "company", domain: "frontier-ai" },
  { finalName: "Zenefits (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Zulily (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "Zuma (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "favorited (a16z)", type: "company", domain: "frontier-ai" },
  { finalName: "k-ID (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "kweliTV (a16z)", type: "company", domain: "vertical-saas" },
  { finalName: "ternwheel (a16z)", type: "company", domain: "infra-devtools" },
];
