// General Catalyst + Accel portfolio batches — net-new entries to add as low-priority targeting (May 7 2026)
// Health/bio, defense, mega-public, acquired/defunct, NFT-gaming-crypto, lifestyle/consumer all filtered out.
// Names follow "Company Name (VC)" convention.
// All entries get priority="low" so they render in the Secondary targets tier.

import type { EntryType, Domain } from "./types";

export interface GcAccelSeed {
  finalName: string;
  type: EntryType;
  domain: Domain;
  source: "general-catalyst" | "accel";
}

export const GENERAL_CATALYST_BATCH_2026_05_07: GcAccelSeed[] = [
  { finalName: "1001 AI (General Catalyst)", type: "company", domain: "frontier-ai", source: "general-catalyst" },
  { finalName: "Aatmunn (General Catalyst)", type: "company", domain: "infra-devtools", source: "general-catalyst" },
  { finalName: "Accordance (General Catalyst)", type: "company", domain: "frontier-ai", source: "general-catalyst" },
  { finalName: "Accrual (General Catalyst)", type: "company", domain: "fintech", source: "general-catalyst" },
  { finalName: "Afori (General Catalyst)", type: "company", domain: "fintech", source: "general-catalyst" },
  { finalName: "AgentMail (General Catalyst)", type: "company", domain: "frontier-ai", source: "general-catalyst" },
  { finalName: "Agora (General Catalyst)", type: "company", domain: "fintech", source: "general-catalyst" },
  { finalName: "Aidoc (General Catalyst)", type: "company", domain: "vertical-saas", source: "general-catalyst" },
  { finalName: "AIM (General Catalyst)", type: "company", domain: "frontier-ai", source: "general-catalyst" },
  { finalName: "Alinea Health (General Catalyst)", type: "company", domain: "vertical-saas", source: "general-catalyst" },
  { finalName: "Allego (General Catalyst)", type: "company", domain: "vertical-saas", source: "general-catalyst" },
  { finalName: "Almanac Labs (General Catalyst)", type: "company", domain: "frontier-ai", source: "general-catalyst" },
  { finalName: "Alsym Energy (General Catalyst)", type: "company", domain: "other", source: "general-catalyst" },
  { finalName: "Alyce (General Catalyst)", type: "company", domain: "vertical-saas", source: "general-catalyst" },
  { finalName: "Amigo (General Catalyst)", type: "company", domain: "frontier-ai", source: "general-catalyst" },
  { finalName: "Argmax (General Catalyst)", type: "company", domain: "frontier-ai", source: "general-catalyst" },
  { finalName: "Arphie (General Catalyst)", type: "company", domain: "frontier-ai", source: "general-catalyst" },
  { finalName: "Array (General Catalyst)", type: "company", domain: "vertical-saas", source: "general-catalyst" },
  { finalName: "Arrcus (General Catalyst)", type: "company", domain: "infra-devtools", source: "general-catalyst" },
  { finalName: "Artie (General Catalyst)", type: "company", domain: "vertical-saas", source: "general-catalyst" },
  { finalName: "AtoB (General Catalyst)", type: "company", domain: "fintech", source: "general-catalyst" },
  { finalName: "August Health (General Catalyst)", type: "company", domain: "vertical-saas", source: "general-catalyst" },
  { finalName: "AuthZed (General Catalyst)", type: "company", domain: "infra-devtools", source: "general-catalyst" },
  { finalName: "autone (General Catalyst)", type: "company", domain: "frontier-ai", source: "general-catalyst" },
  { finalName: "Autoscience (General Catalyst)", type: "company", domain: "frontier-ai", source: "general-catalyst" },
  { finalName: "Awardco (General Catalyst)", type: "company", domain: "vertical-saas", source: "general-catalyst" },
  { finalName: "axiTrust (General Catalyst)", type: "company", domain: "fintech", source: "general-catalyst" },
  { finalName: "Ayr Energy (General Catalyst)", type: "company", domain: "other", source: "general-catalyst" },
  { finalName: "B12 (General Catalyst)", type: "company", domain: "vertical-saas", source: "general-catalyst" },
  { finalName: "BBN (General Catalyst)", type: "company", domain: "vertical-saas", source: "general-catalyst" },
  { finalName: "beautiful.ai (General Catalyst)", type: "company", domain: "frontier-ai", source: "general-catalyst" },
  { finalName: "Billion Hearts (General Catalyst)", type: "company", domain: "vertical-saas", source: "general-catalyst" },
  { finalName: "Bolna (General Catalyst)", type: "company", domain: "frontier-ai", source: "general-catalyst" },
  { finalName: "Brighter (General Catalyst)", type: "company", domain: "vertical-saas", source: "general-catalyst" },
  { finalName: "Carma (General Catalyst)", type: "company", domain: "vertical-saas", source: "general-catalyst" },
  { finalName: "Casana (General Catalyst)", type: "company", domain: "vertical-saas", source: "general-catalyst" },
  { finalName: "CashFlo (General Catalyst)", type: "company", domain: "fintech", source: "general-catalyst" },
  { finalName: "Catalant (General Catalyst)", type: "company", domain: "vertical-saas", source: "general-catalyst" },
  { finalName: "ChannelEngine (General Catalyst)", type: "company", domain: "vertical-saas", source: "general-catalyst" },
  { finalName: "Civic Roundtable (General Catalyst)", type: "company", domain: "vertical-saas", source: "general-catalyst" },
  { finalName: "Clara (General Catalyst)", type: "company", domain: "fintech", source: "general-catalyst" },
  { finalName: "Clarabridge (General Catalyst)", type: "company", domain: "vertical-saas", source: "general-catalyst" },
  { finalName: "Claros (General Catalyst)", type: "company", domain: "other", source: "general-catalyst" },
  { finalName: "Cloaked (General Catalyst)", type: "company", domain: "infra-devtools", source: "general-catalyst" },
  { finalName: "Conntour (General Catalyst)", type: "company", domain: "frontier-ai", source: "general-catalyst" },
  { finalName: "Coolant (General Catalyst)", type: "company", domain: "other", source: "general-catalyst" },
  { finalName: "Crescendo (General Catalyst)", type: "company", domain: "frontier-ai", source: "general-catalyst" },
  { finalName: "Dwelly (General Catalyst)", type: "company", domain: "frontier-ai", source: "general-catalyst" },
  { finalName: "ecton (General Catalyst)", type: "company", domain: "vertical-saas", source: "general-catalyst" },
  { finalName: "Electio (General Catalyst)", type: "company", domain: "other", source: "general-catalyst" },
  { finalName: "Elemental (General Catalyst)", type: "company", domain: "other", source: "general-catalyst" },
  { finalName: "Elevate K-12 (General Catalyst)", type: "company", domain: "vertical-saas", source: "general-catalyst" },
  { finalName: "Elysium (General Catalyst)", type: "company", domain: "vertical-saas", source: "general-catalyst" },
  { finalName: "Emidat (General Catalyst)", type: "company", domain: "other", source: "general-catalyst" },
  { finalName: "encentive (General Catalyst)", type: "company", domain: "other", source: "general-catalyst" },
  { finalName: "Enigma Analytics (General Catalyst)", type: "company", domain: "infra-devtools", source: "general-catalyst" },
  { finalName: "Eudia (General Catalyst)", type: "company", domain: "frontier-ai", source: "general-catalyst" },
  { finalName: "Expanso (General Catalyst)", type: "company", domain: "infra-devtools", source: "general-catalyst" },
  { finalName: "Feedvisor (General Catalyst)", type: "company", domain: "vertical-saas", source: "general-catalyst" },
  { finalName: "Félix (General Catalyst)", type: "company", domain: "fintech", source: "general-catalyst" },
  { finalName: "Fifteenth (General Catalyst)", type: "company", domain: "fintech", source: "general-catalyst" },
  { finalName: "Finom (General Catalyst)", type: "company", domain: "fintech", source: "general-catalyst" },
  { finalName: "First Street (General Catalyst)", type: "company", domain: "other", source: "general-catalyst" },
  { finalName: "Fourier (General Catalyst)", type: "company", domain: "other", source: "general-catalyst" },
  { finalName: "Fundbox (General Catalyst)", type: "company", domain: "fintech", source: "general-catalyst" },
  { finalName: "General Intuition (General Catalyst)", type: "company", domain: "frontier-ai", source: "general-catalyst" },
  { finalName: "Genial Care (General Catalyst)", type: "company", domain: "vertical-saas", source: "general-catalyst" },
  { finalName: "Geordie (General Catalyst)", type: "company", domain: "frontier-ai", source: "general-catalyst" },
  { finalName: "GoodStack (General Catalyst)", type: "company", domain: "infra-devtools", source: "general-catalyst" },
  { finalName: "Guardhat (General Catalyst)", type: "company", domain: "vertical-saas", source: "general-catalyst" },
  { finalName: "Guild (General Catalyst)", type: "company", domain: "vertical-saas", source: "general-catalyst" },
  { finalName: "Heyday (General Catalyst)", type: "company", domain: "infra-devtools", source: "general-catalyst" },
  { finalName: "Highlight (General Catalyst)", type: "company", domain: "frontier-ai", source: "general-catalyst" },
  { finalName: "Highway9 (General Catalyst)", type: "company", domain: "infra-devtools", source: "general-catalyst" },
  { finalName: "Hiro (General Catalyst)", type: "company", domain: "fintech", source: "general-catalyst" },
  { finalName: "Housecall Pro (General Catalyst)", type: "company", domain: "vertical-saas", source: "general-catalyst" },
  { finalName: "Human Behavior (General Catalyst)", type: "company", domain: "frontier-ai", source: "general-catalyst" },
  { finalName: "Humans Anonymous (General Catalyst)", type: "company", domain: "vertical-saas", source: "general-catalyst" },
  { finalName: "Integral (General Catalyst)", type: "company", domain: "fintech", source: "general-catalyst" },
  { finalName: "Ionic (General Catalyst)", type: "company", domain: "vertical-saas", source: "general-catalyst" },
  { finalName: "Iru (General Catalyst)", type: "company", domain: "infra-devtools", source: "general-catalyst" },
  { finalName: "Jigso (General Catalyst)", type: "company", domain: "infra-devtools", source: "general-catalyst" },
  { finalName: "JuliaHub (General Catalyst)", type: "company", domain: "infra-devtools", source: "general-catalyst" },
  { finalName: "Kick (General Catalyst)", type: "company", domain: "frontier-ai", source: "general-catalyst" },
  { finalName: "Kite (General Catalyst)", type: "company", domain: "frontier-ai", source: "general-catalyst" },
  { finalName: "L2 (General Catalyst)", type: "company", domain: "fintech", source: "general-catalyst" },
  { finalName: "Ladder (General Catalyst)", type: "company", domain: "vertical-saas", source: "general-catalyst" },
  { finalName: "Langdock (General Catalyst)", type: "company", domain: "frontier-ai", source: "general-catalyst" },
  { finalName: "Lean Technologies (General Catalyst)", type: "company", domain: "fintech", source: "general-catalyst" },
  { finalName: "Lessen (General Catalyst)", type: "company", domain: "infra-devtools", source: "general-catalyst" },
  { finalName: "Localyze (General Catalyst)", type: "company", domain: "infra-devtools", source: "general-catalyst" },
  { finalName: "Loci (General Catalyst)", type: "company", domain: "frontier-ai", source: "general-catalyst" },
  { finalName: "Logz.io (General Catalyst)", type: "company", domain: "infra-devtools", source: "general-catalyst" },
  { finalName: "Long Lake (General Catalyst)", type: "company", domain: "frontier-ai", source: "general-catalyst" },
  { finalName: "Lume (General Catalyst)", type: "company", domain: "frontier-ai", source: "general-catalyst" },
  { finalName: "Magma (General Catalyst)", type: "company", domain: "infra-devtools", source: "general-catalyst" },
  { finalName: "Mainspring Energy (General Catalyst)", type: "company", domain: "other", source: "general-catalyst" },
  { finalName: "Martian (General Catalyst)", type: "company", domain: "frontier-ai", source: "general-catalyst" },
  { finalName: "Material Bank (General Catalyst)", type: "company", domain: "vertical-saas", source: "general-catalyst" },
  { finalName: "Menlo (General Catalyst)", type: "company", domain: "infra-devtools", source: "general-catalyst" },
  { finalName: "Menlo Security (General Catalyst)", type: "company", domain: "infra-devtools", source: "general-catalyst" },
  { finalName: "Minio (General Catalyst)", type: "company", domain: "infra-devtools", source: "general-catalyst" },
  { finalName: "Moda (General Catalyst)", type: "company", domain: "frontier-ai", source: "general-catalyst" },
  { finalName: "Moonvalley (General Catalyst)", type: "company", domain: "frontier-ai", source: "general-catalyst" },
  { finalName: "Mosaic (General Catalyst)", type: "company", domain: "fintech", source: "general-catalyst" },
  { finalName: "m-Qube (General Catalyst)", type: "company", domain: "vertical-saas", source: "general-catalyst" },
  { finalName: "Nace.AI (General Catalyst)", type: "company", domain: "frontier-ai", source: "general-catalyst" },
  { finalName: "NaroIQ (General Catalyst)", type: "company", domain: "fintech", source: "general-catalyst" },
  { finalName: "Native Security (General Catalyst)", type: "company", domain: "infra-devtools", source: "general-catalyst" },
  { finalName: "NewStore (General Catalyst)", type: "company", domain: "vertical-saas", source: "general-catalyst" },
  { finalName: "Nirvana (General Catalyst)", type: "company", domain: "vertical-saas", source: "general-catalyst" },
  { finalName: "Numos (General Catalyst)", type: "company", domain: "frontier-ai", source: "general-catalyst" },
  { finalName: "Octane AI (General Catalyst)", type: "company", domain: "frontier-ai", source: "general-catalyst" },
  { finalName: "OGSystems (General Catalyst)", type: "company", domain: "vertical-saas", source: "general-catalyst" },
  { finalName: "OneSchema (General Catalyst)", type: "company", domain: "infra-devtools", source: "general-catalyst" },
  { finalName: "Orchard Robotics (General Catalyst)", type: "company", domain: "other", source: "general-catalyst" },
  { finalName: "Origin (General Catalyst)", type: "company", domain: "fintech", source: "general-catalyst" },
  { finalName: "Pacific Fusion (General Catalyst)", type: "company", domain: "other", source: "general-catalyst" },
  { finalName: "Pantomath (General Catalyst)", type: "company", domain: "frontier-ai", source: "general-catalyst" },
  { finalName: "Parallax (General Catalyst)", type: "company", domain: "fintech", source: "general-catalyst" },
  { finalName: "Parloa (General Catalyst)", type: "company", domain: "frontier-ai", source: "general-catalyst" },
  { finalName: "Paydiant (General Catalyst)", type: "company", domain: "fintech", source: "general-catalyst" },
  { finalName: "Percent (General Catalyst)", type: "company", domain: "infra-devtools", source: "general-catalyst" },
  { finalName: "Perk (General Catalyst)", type: "company", domain: "vertical-saas", source: "general-catalyst" },
  { finalName: "Ping (General Catalyst)", type: "company", domain: "infra-devtools", source: "general-catalyst" },
  { finalName: "Please (General Catalyst)", type: "company", domain: "frontier-ai", source: "general-catalyst" },
  { finalName: "Podqi (General Catalyst)", type: "company", domain: "frontier-ai", source: "general-catalyst" },
  { finalName: "Ponto (General Catalyst)", type: "company", domain: "fintech", source: "general-catalyst" },
  { finalName: "Prelay (General Catalyst)", type: "company", domain: "vertical-saas", source: "general-catalyst" },
  { finalName: "Prime Meridian (General Catalyst)", type: "company", domain: "fintech", source: "general-catalyst" },
  { finalName: "Prosimo (General Catalyst)", type: "company", domain: "vertical-saas", source: "general-catalyst" },
  { finalName: "PRYPCO (General Catalyst)", type: "company", domain: "fintech", source: "general-catalyst" },
  { finalName: "Puzzle (General Catalyst)", type: "company", domain: "fintech", source: "general-catalyst" },
  { finalName: "PvX Partners (General Catalyst)", type: "company", domain: "fintech", source: "general-catalyst" },
  { finalName: "QFEX (General Catalyst)", type: "company", domain: "fintech", source: "general-catalyst" },
  { finalName: "Quo (General Catalyst)", type: "company", domain: "vertical-saas", source: "general-catalyst" },
  { finalName: "R2 (General Catalyst)", type: "company", domain: "fintech", source: "general-catalyst" },
  { finalName: "Rakuten (General Catalyst)", type: "company", domain: "vertical-saas", source: "general-catalyst" },
  { finalName: "Ranger (General Catalyst)", type: "company", domain: "frontier-ai", source: "general-catalyst" },
  { finalName: "Re:Build (General Catalyst)", type: "company", domain: "other", source: "general-catalyst" },
  { finalName: "Refuel (General Catalyst)", type: "company", domain: "frontier-ai", source: "general-catalyst" },
  { finalName: "Remesh (General Catalyst)", type: "company", domain: "vertical-saas", source: "general-catalyst" },
  { finalName: "RemNote (General Catalyst)", type: "company", domain: "vertical-saas", source: "general-catalyst" },
  { finalName: "Resilience (General Catalyst)", type: "company", domain: "infra-devtools", source: "general-catalyst" },
  { finalName: "Reveal Imaging (General Catalyst)", type: "company", domain: "vertical-saas", source: "general-catalyst" },
  { finalName: "Rezonant (General Catalyst)", type: "company", domain: "frontier-ai", source: "general-catalyst" },
  { finalName: "Rossum (General Catalyst)", type: "company", domain: "infra-devtools", source: "general-catalyst" },
  { finalName: "Safari AI (General Catalyst)", type: "company", domain: "frontier-ai", source: "general-catalyst" },
  { finalName: "Samara (General Catalyst)", type: "company", domain: "vertical-saas", source: "general-catalyst" },
  { finalName: "Scalar (General Catalyst)", type: "company", domain: "frontier-ai", source: "general-catalyst" },
  { finalName: "Securiti (General Catalyst)", type: "company", domain: "infra-devtools", source: "general-catalyst" },
  { finalName: "Semantic (General Catalyst)", type: "company", domain: "vertical-saas", source: "general-catalyst" },
  { finalName: "Shelf Engine (General Catalyst)", type: "company", domain: "vertical-saas", source: "general-catalyst" },
  { finalName: "Shift (General Catalyst)", type: "company", domain: "vertical-saas", source: "general-catalyst" },
  { finalName: "Signal Advisors (General Catalyst)", type: "company", domain: "fintech", source: "general-catalyst" },
  { finalName: "Singular (General Catalyst)", type: "company", domain: "infra-devtools", source: "general-catalyst" },
  { finalName: "Slate Auto (General Catalyst)", type: "company", domain: "other", source: "general-catalyst" },
  { finalName: "Slide (General Catalyst)", type: "company", domain: "infra-devtools", source: "general-catalyst" },
  { finalName: "Smalt (General Catalyst)", type: "company", domain: "other", source: "general-catalyst" },
  { finalName: "Soff (General Catalyst)", type: "company", domain: "frontier-ai", source: "general-catalyst" },
  { finalName: "Spiral (General Catalyst)", type: "company", domain: "frontier-ai", source: "general-catalyst" },
  { finalName: "Standard Bots (General Catalyst)", type: "company", domain: "other", source: "general-catalyst" },
  { finalName: "Standard Kernel (General Catalyst)", type: "company", domain: "frontier-ai", source: "general-catalyst" },
  { finalName: "Step (General Catalyst)", type: "company", domain: "fintech", source: "general-catalyst" },
  { finalName: "Stilla (General Catalyst)", type: "company", domain: "frontier-ai", source: "general-catalyst" },
  { finalName: "Stori (General Catalyst)", type: "company", domain: "fintech", source: "general-catalyst" },
  { finalName: "Strawberry (General Catalyst)", type: "company", domain: "frontier-ai", source: "general-catalyst" },
  { finalName: "SunBorne (General Catalyst)", type: "company", domain: "other", source: "general-catalyst" },
  { finalName: "SupportLogic (General Catalyst)", type: "company", domain: "vertical-saas", source: "general-catalyst" },
  { finalName: "Symbolica (General Catalyst)", type: "company", domain: "frontier-ai", source: "general-catalyst" },
  { finalName: "Tabs (General Catalyst)", type: "company", domain: "infra-devtools", source: "general-catalyst" },
  { finalName: "Taurus (General Catalyst)", type: "company", domain: "vertical-saas", source: "general-catalyst" },
  { finalName: "Teambridge (General Catalyst)", type: "company", domain: "infra-devtools", source: "general-catalyst" },
  { finalName: "Teamworks (General Catalyst)", type: "company", domain: "vertical-saas", source: "general-catalyst" },
  { finalName: "TellTail (General Catalyst)", type: "company", domain: "infra-devtools", source: "general-catalyst" },
  { finalName: "Tempus Ex (General Catalyst)", type: "company", domain: "other", source: "general-catalyst" },
  { finalName: "Terragia (General Catalyst)", type: "company", domain: "infra-devtools", source: "general-catalyst" },
  { finalName: "The Interaction Company of California (General Catalyst)", type: "company", domain: "frontier-ai", source: "general-catalyst" },
  { finalName: "The Predictive Index (General Catalyst)", type: "company", domain: "vertical-saas", source: "general-catalyst" },
  { finalName: "Tidelift (General Catalyst)", type: "company", domain: "infra-devtools", source: "general-catalyst" },
  { finalName: "Tigris (General Catalyst)", type: "company", domain: "infra-devtools", source: "general-catalyst" },
  { finalName: "Titan Invest (General Catalyst)", type: "company", domain: "fintech", source: "general-catalyst" },
  { finalName: "Tiyaro (General Catalyst)", type: "company", domain: "infra-devtools", source: "general-catalyst" },
  { finalName: "Tractian (General Catalyst)", type: "company", domain: "other", source: "general-catalyst" },
  { finalName: "Trellis (General Catalyst)", type: "company", domain: "fintech", source: "general-catalyst" },
  { finalName: "Uni (General Catalyst)", type: "company", domain: "fintech", source: "general-catalyst" },
  { finalName: "Varda (General Catalyst)", type: "company", domain: "other", source: "general-catalyst" },
  { finalName: "Verta (General Catalyst)", type: "company", domain: "infra-devtools", source: "general-catalyst" },
  { finalName: "Visor (General Catalyst)", type: "company", domain: "infra-devtools", source: "general-catalyst" },
  { finalName: "Vital Lyfe (General Catalyst)", type: "company", domain: "other", source: "general-catalyst" },
  { finalName: "Viva Translate (General Catalyst)", type: "company", domain: "infra-devtools", source: "general-catalyst" },
  { finalName: "Vivere (General Catalyst)", type: "company", domain: "infra-devtools", source: "general-catalyst" },
  { finalName: "Zego (General Catalyst)", type: "company", domain: "fintech", source: "general-catalyst" },
  { finalName: "Zerigo (General Catalyst)", type: "company", domain: "infra-devtools", source: "general-catalyst" },
  { finalName: "Zero RFI (General Catalyst)", type: "company", domain: "other", source: "general-catalyst" },
  { finalName: "ZET (General Catalyst)", type: "company", domain: "vertical-saas", source: "general-catalyst" },
  { finalName: "Zip Security (General Catalyst)", type: "company", domain: "infra-devtools", source: "general-catalyst" },
];

export const ACCEL_BATCH_2026_05_07: GcAccelSeed[] = [
  { finalName: "Aavenir (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Ada Support (Accel)", type: "company", domain: "frontier-ai", source: "accel" },
  { finalName: "AegisAI (Accel)", type: "company", domain: "frontier-ai", source: "accel" },
  { finalName: "Agave (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Agrostar (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "AirKit (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "Airmeet (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Akridata (Accel)", type: "company", domain: "frontier-ai", source: "accel" },
  { finalName: "Ally (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Altinity (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Ampool (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Anar (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "ANSR (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Anyfin (Accel)", type: "company", domain: "fintech", source: "accel" },
  { finalName: "Aorato (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "ApnaMart (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Appbrew (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Appsmith (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "Aptly (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Aramya (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Arista (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Arivihan (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Armadin (Accel)", type: "company", domain: "frontier-ai", source: "accel" },
  { finalName: "Ascend.io (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "Astro (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Atrato (Accel)", type: "company", domain: "fintech", source: "accel" },
  { finalName: "atSpoke (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "Axle Energy (Accel)", type: "company", domain: "other", source: "accel" },
  { finalName: "Axonius (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "Bachatt (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Beek (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "BeReal (Accel)", type: "company", domain: "other", source: "accel" },
  { finalName: "Bevy (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Binocs (Accel)", type: "company", domain: "fintech", source: "accel" },
  { finalName: "Blackpoint (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "Blameless (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "Blue Jeans Network (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "Born (Accel)", type: "company", domain: "other", source: "accel" },
  { finalName: "Borqs (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Brick&Bolt (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Bridgetown Research (Accel)", type: "company", domain: "frontier-ai", source: "accel" },
  { finalName: "Brik (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Bryter (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "CallSign (Accel)", type: "company", domain: "fintech", source: "accel" },
  { finalName: "Campfire (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "CardSpring (Accel)", type: "company", domain: "fintech", source: "accel" },
  { finalName: "CareStack (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Cartwheel (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Catalyst (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Causal (Accel)", type: "company", domain: "fintech", source: "accel" },
  { finalName: "Cdata (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "Chaos (Accel)", type: "company", domain: "other", source: "accel" },
  { finalName: "Charles (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Checkly (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "Cinder (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "CleverTap (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "ClockWise (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "Code Metal (Accel)", type: "company", domain: "frontier-ai", source: "accel" },
  { finalName: "Cognite (Accel)", type: "company", domain: "other", source: "accel" },
  { finalName: "Cogoport (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Cohesity (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "Complete (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "ConductorOne (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "Conduktor (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "Corsa (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Coverfox (Accel)", type: "company", domain: "fintech", source: "accel" },
  { finalName: "Creator Stack (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Credgenics (Accel)", type: "company", domain: "fintech", source: "accel" },
  { finalName: "CrowdAnalytix (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "Cycognito (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "Dash0 (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "Databand (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "Dealer Dot Com (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "DecisionLink (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Deep Rooted (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "DeepMap (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "Delightree (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Demisto (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "depthfirst (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "Deserve (Accel)", type: "company", domain: "fintech", source: "accel" },
  { finalName: "Despegar (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Detect (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "Dezerv (Accel)", type: "company", domain: "fintech", source: "accel" },
  { finalName: "Dovetail (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Drip Capital (Accel)", type: "company", domain: "fintech", source: "accel" },
  { finalName: "e6data (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "Effectiv (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "Ema (Accel)", type: "company", domain: "frontier-ai", source: "accel" },
  { finalName: "Entytle (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Ermetic (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "Facet (Accel)", type: "company", domain: "fintech", source: "accel" },
  { finalName: "Fibr (Accel)", type: "company", domain: "other", source: "accel" },
  { finalName: "Fictiv (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Filigran (Accel)", type: "company", domain: "frontier-ai", source: "accel" },
  { finalName: "Finaloop (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Finbots.AI (Accel)", type: "company", domain: "fintech", source: "accel" },
  { finalName: "Finrep (Accel)", type: "company", domain: "fintech", source: "accel" },
  { finalName: "FlyFin (Accel)", type: "company", domain: "fintech", source: "accel" },
  { finalName: "Fortify (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "Fortigo (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Forus Health (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Fuse (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Gamma (Accel)", type: "company", domain: "frontier-ai", source: "accel" },
  { finalName: "Gel Data (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "Genesis (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "Gloat (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "H Company (Accel)", type: "company", domain: "frontier-ai", source: "accel" },
  { finalName: "Haber (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Hashnode (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Hera (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Higgsfield (Accel)", type: "company", domain: "frontier-ai", source: "accel" },
  { finalName: "Higo (Accel)", type: "company", domain: "frontier-ai", source: "accel" },
  { finalName: "Hotelogix (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Hubble (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Infra.Market (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Invoca (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Jellyfish (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Jify (Accel)", type: "company", domain: "fintech", source: "accel" },
  { finalName: "Juspay (Accel)", type: "company", domain: "fintech", source: "accel" },
  { finalName: "Kirusa (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Knight Fintech (Accel)", type: "company", domain: "fintech", source: "accel" },
  { finalName: "Knoetic (Accel)", type: "company", domain: "fintech", source: "accel" },
  { finalName: "Komodor (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "Leap (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Ledger Investing (Accel)", type: "company", domain: "fintech", source: "accel" },
  { finalName: "Legion (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Legora (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "LetsVenture (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Lica (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Lightdash (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "Lighthouse (Accel)", type: "company", domain: "frontier-ai", source: "accel" },
  { finalName: "Lightrun (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "Locofy (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "LogicLoop (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "Lower (Accel)", type: "company", domain: "fintech", source: "accel" },
  { finalName: "Luciq (Accel)", type: "company", domain: "frontier-ai", source: "accel" },
  { finalName: "Luko (Accel)", type: "company", domain: "fintech", source: "accel" },
  { finalName: "Makelog (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "Medigo (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Mihup (Accel)", type: "company", domain: "fintech", source: "accel" },
  { finalName: "ModernLoop (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Monte Carlo (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "MyWear (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Nanonets (Accel)", type: "company", domain: "frontier-ai", source: "accel" },
  { finalName: "Napkin.AI (Accel)", type: "company", domain: "frontier-ai", source: "accel" },
  { finalName: "Narvar (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Nebius (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "Ninjacart (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Nory (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Nova (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Nuance Labs (Accel)", type: "company", domain: "frontier-ai", source: "accel" },
  { finalName: "Nuitee (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Nurix AI (Accel)", type: "company", domain: "frontier-ai", source: "accel" },
  { finalName: "Oasis (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "Octarine (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "Omnea (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "OpenFX (Accel)", type: "company", domain: "fintech", source: "accel" },
  { finalName: "OpenGamma (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "Origami Logic (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "OSlash (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Osmo (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "OtterTune (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "OzForex (Accel)", type: "company", domain: "fintech", source: "accel" },
  { finalName: "Packlink (Accel)", type: "company", domain: "fintech", source: "accel" },
  { finalName: "Paper (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Pave Bank (Accel)", type: "company", domain: "fintech", source: "accel" },
  { finalName: "Payfit (Accel)", type: "company", domain: "fintech", source: "accel" },
  { finalName: "Pismo (Accel)", type: "company", domain: "fintech", source: "accel" },
  { finalName: "Plex Systems (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Podium (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Poggio Labs (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Polar (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Polars (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Pond5 (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Port (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "Powerplay (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "PRED (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Presentations.ai (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "PrimaryIO (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "Process Street (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Productiv (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "ProjectDiscovery (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "Propeller Aero (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Prophet Security (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "Public (Accel)", type: "company", domain: "fintech", source: "accel" },
  { finalName: "Qriously (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "QTalk (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Quokka Sports (Accel)", type: "company", domain: "other", source: "accel" },
  { finalName: "RadixArk (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "Rainforest (Accel)", type: "company", domain: "fintech", source: "accel" },
  { finalName: "RapidCanvas (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "RapidClaims (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Raycast (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "ReadMe.io (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "RecommerceX (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Recraft (Accel)", type: "company", domain: "frontier-ai", source: "accel" },
  { finalName: "relateIQ (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "RiskRecon (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "Rows (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "Rupeek (Accel)", type: "company", domain: "fintech", source: "accel" },
  { finalName: "Sainapse (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Samunnati (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Sapiom (Accel)", type: "company", domain: "fintech", source: "accel" },
  { finalName: "Scimplify (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Scratchpad (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "Scripbox (Accel)", type: "company", domain: "fintech", source: "accel" },
  { finalName: "Securden (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "Seezo (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "Shift Technology (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Shivalik Bank (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Shorebird (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "SilverRail (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Simility (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "Simplismart (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "simsim (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Skeps (Accel)", type: "company", domain: "fintech", source: "accel" },
  { finalName: "Skipjaq (Accel)", type: "company", domain: "other", source: "accel" },
  { finalName: "Slintel (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "SmallStep (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "Solda.ai (Accel)", type: "company", domain: "frontier-ai", source: "accel" },
  { finalName: "SolveAI (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Soma (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Spendflo (Accel)", type: "company", domain: "fintech", source: "accel" },
  { finalName: "Spindle Technologies (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "Split (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "SpringSource (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "Sprinto (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Stacklok (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "Styra (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "Super Payments (Accel)", type: "company", domain: "fintech", source: "accel" },
  { finalName: "Superfuel AI (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Surf AI (Accel)", type: "company", domain: "frontier-ai", source: "accel" },
  { finalName: "Swan (Accel)", type: "company", domain: "fintech", source: "accel" },
  { finalName: "Swypex (Accel)", type: "company", domain: "fintech", source: "accel" },
  { finalName: "Synthflow Ai (Accel)", type: "company", domain: "frontier-ai", source: "accel" },
  { finalName: "Taascom (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Taito.ai (Accel)", type: "company", domain: "frontier-ai", source: "accel" },
  { finalName: "Taxdoo (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Testsigma (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Teya (Accel)", type: "company", domain: "fintech", source: "accel" },
  { finalName: "Thinking Machines (Accel)", type: "company", domain: "frontier-ai", source: "accel" },
  { finalName: "ThreeFlow (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Tines (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "Tonkean (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Trace Data (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Tracebit (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "Tracxn (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "Transit (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Travelstop (Accel)", type: "company", domain: "fintech", source: "accel" },
  { finalName: "umrahme (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Uni Cards (Accel)", type: "company", domain: "fintech", source: "accel" },
  { finalName: "Uniqode (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Unit (Accel)", type: "company", domain: "fintech", source: "accel" },
  { finalName: "UnitQ (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "Uppercase (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "USPL Wrogn (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Val Town (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "Vaya (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "VComply (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Vectra (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "Vedantu (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Vega Security (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Venue (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Venwiz (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Veriff (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Veza (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "Vinculum (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Virgio (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "VISO (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Vivun (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "vlt (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "VoidZero (Accel)", type: "company", domain: "frontier-ai", source: "accel" },
  { finalName: "Vorlon (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
  { finalName: "Xalts (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "Xfactor.io (Accel)", type: "company", domain: "vertical-saas", source: "accel" },
  { finalName: "YapStone (Accel)", type: "company", domain: "fintech", source: "accel" },
  { finalName: "Zebrium (Accel)", type: "company", domain: "infra-devtools", source: "accel" },
];
