// Deterministic seed for the top ~150 well-known pools. Anything not in
// POOL_CATEGORIES defaults to "other". Regenerate/extend with the LLM
// pass via `node scripts/build-pool-categories.mjs` once you have
// ANTHROPIC_API_KEY set in .env.local.

export type PoolCategory =
  | "foundation-lab"
  | "big-tech"
  | "ai-startup"
  | "data-infra"
  | "devtools"
  | "fintech"
  | "trading"
  | "robotics"
  | "defense"
  | "research-lab"
  | "university"
  | "consumer"
  | "healthtech"
  | "other";

export const CATEGORY_LABELS: Record<PoolCategory, string> = {
  "foundation-lab": "Foundation labs",
  "big-tech": "Big tech",
  "ai-startup": "AI startups",
  "data-infra": "Data / infra",
  "devtools": "Devtools",
  "fintech": "Fintech",
  "trading": "Trading",
  "robotics": "Robotics",
  "defense": "Defense",
  "research-lab": "Research labs",
  "university": "Universities",
  "consumer": "Consumer",
  "healthtech": "Health tech",
  "other": "Other",
};

export const CATEGORY_ORDER: PoolCategory[] = [
  "foundation-lab",
  "ai-startup",
  "big-tech",
  "data-infra",
  "devtools",
  "fintech",
  "trading",
  "robotics",
  "defense",
  "research-lab",
  "university",
  "consumer",
  "healthtech",
  "other",
];

export const POOL_CATEGORIES: Record<string, PoolCategory> = {
  // ── Foundation labs ─────────────────────────────────────────
  "OpenAI": "foundation-lab",
  "Anthropic": "foundation-lab",
  "xAI": "foundation-lab",
  "SpaceXAI": "foundation-lab",
  "Google DeepMind": "foundation-lab",
  "Deepmind": "foundation-lab",
  "Mistral AI": "foundation-lab",
  "Cohere": "foundation-lab",
  "Thinking Machines Lab": "foundation-lab",
  "Character.AI": "foundation-lab",
  "World Labs": "foundation-lab",
  "Liquid AI": "foundation-lab",
  "SambaNova Systems": "foundation-lab",
  "Reka": "foundation-lab",
  "Inflection": "foundation-lab",
  "Microsoft AI": "foundation-lab",

  // ── Big tech ────────────────────────────────────────────────
  "Meta": "big-tech",
  "Facebook": "big-tech",
  "Instagram": "big-tech",
  "Google": "big-tech",
  "YouTube": "big-tech",
  "Amazon": "big-tech",
  "Amazon Web Services (AWS)": "big-tech",
  "AWS": "big-tech",
  "Apple": "big-tech",
  "Microsoft": "big-tech",
  "NVIDIA": "big-tech",
  "Nvidia": "big-tech",
  "Netflix": "big-tech",
  "TikTok": "big-tech",
  "ByteDance": "big-tech",
  "Snap Inc.": "big-tech",
  "LinkedIn": "big-tech",
  "Salesforce": "big-tech",
  "Slack": "big-tech",
  "ServiceNow": "big-tech",
  "Adobe": "big-tech",
  "Cisco": "big-tech",
  "Atlassian": "big-tech",
  "Dropbox": "big-tech",
  "HubSpot": "big-tech",
  "Intuit": "big-tech",
  "Spotify": "big-tech",
  "X": "big-tech",
  "Oracle": "big-tech",
  "IBM": "big-tech",
  "Veeva Systems": "big-tech",
  "Twitch": "big-tech",

  // ── AI startups ─────────────────────────────────────────────
  "Perplexity": "ai-startup",
  "Mercor": "ai-startup",
  "Decagon": "ai-startup",
  "Sierra": "ai-startup",
  "Cognition": "ai-startup",
  "Harvey": "ai-startup",
  "Codeium": "ai-startup",
  "Cursor": "ai-startup",
  "Anyscale": "ai-startup",
  "Together AI": "ai-startup",
  "Etched": "ai-startup",
  "Cartesia": "ai-startup",
  "Suno": "ai-startup",
  "Nooks": "ai-startup",
  "Moveworks": "ai-startup",
  "Clay": "ai-startup",
  "LangChain": "ai-startup",
  "EliseAI": "ai-startup",
  "Snorkel AI": "ai-startup",
  "Rox": "ai-startup",
  "Nominal": "ai-startup",
  "Actively AI": "ai-startup",
  "Rogo": "ai-startup",
  "Resolve AI": "ai-startup",
  "Baseten": "ai-startup",
  "Factory": "ai-startup",
  "HeyGen": "ai-startup",
  "Otter.ai": "ai-startup",
  "Tennr": "ai-startup",
  "InstaLILY AI": "ai-startup",
  "Watershed": "ai-startup",
  "Magic": "ai-startup",
  "Fireworks AI": "ai-startup",
  "Chalk": "ai-startup",
  "Reve": "ai-startup",
  "Arize AI": "ai-startup",
  "DatologyAI": "ai-startup",
  "Doppel": "ai-startup",
  "Serval": "ai-startup",
  "Salient": "ai-startup",
  "Distyl AI": "ai-startup",
  "Abacus.AI": "ai-startup",
  "Augment Code": "ai-startup",
  "Transluce": "ai-startup",
  "Goodfire": "ai-startup",
  "Pika": "ai-startup",
  "Vultron": "ai-startup",
  "Hebbia": "ai-startup",
  "Tavus": "ai-startup",
  "ElevenLabs": "ai-startup",
  "Scale AI": "ai-startup",
  "Glean": "ai-startup",
  "Adept": "ai-startup",
  "Physical Intelligence": "ai-startup",
  "Applied Compute": "ai-startup",
  "Surge AI": "ai-startup",
  "Mechanize, Inc.": "ai-startup",
  "Latent": "ai-startup",
  "David AI": "ai-startup",
  "Poetic": "ai-startup",
  "AfterQuery": "ai-startup",
  "Unify": "ai-startup",
  "Traversal": "ai-startup",
  "Datacurve": "ai-startup",
  "Rilla": "ai-startup",
  "Assembled": "ai-startup",
  "Profound": "ai-startup",
  "Netic": "ai-startup",
  "Reevo": "ai-startup",
  "OpenEvidence": "ai-startup",
  "Listen Labs": "ai-startup",
  "Browserbase": "ai-startup",
  "Corridor": "ai-startup",
  "Adaptive Security": "ai-startup",
  "Outtake": "ai-startup",
  "Vocara": "ai-startup",
  "Medra": "ai-startup",
  "Fleet AI, Inc.": "ai-startup",
  "Cogent Security": "ai-startup",
  "Yuzu": "ai-startup",
  "Roadrunner": "ai-startup",
  "Silna": "ai-startup",
  "Auctor": "ai-startup",
  "&AI": "ai-startup",
  "Mintlify": "ai-startup",
  "Neo": "ai-startup",

  // ── Data / infra ────────────────────────────────────────────
  "Databricks": "data-infra",
  "Snowflake": "data-infra",
  "Palantir Technologies": "data-infra",
  "Palantir": "data-infra",
  "Datadog": "data-infra",
  "MongoDB": "data-infra",
  "Crusoe": "data-infra",
  "Cockroach Labs": "data-infra",
  "Hightouch": "data-infra",
  "Sigma Computing": "data-infra",
  "C3 AI": "data-infra",
  "Fastly": "data-infra",
  "Nutanix": "data-infra",
  "InterSystems": "data-infra",
  "Vanta": "data-infra",
  "Vectra AI": "data-infra",
  "Palo Alto Networks": "data-infra",
  "Rubrik": "data-infra",
  "Rubrik, Inc.": "data-infra",
  "Okta": "data-infra",
  "Semgrep": "data-infra",
  "Abnormal AI": "data-infra",
  "Fluidstack": "data-infra",
  "Moloco": "data-infra",

  // ── Devtools ────────────────────────────────────────────────
  "Figma": "devtools",
  "Notion": "devtools",
  "Vercel": "devtools",
  "Retool": "devtools",
  "Airtable": "devtools",
  "Replit": "devtools",
  "Warp": "devtools",
  "Sentry": "devtools",
  "Coda": "devtools",
  "Webflow": "devtools",
  "Superhuman": "devtools",
  "Merge": "devtools",
  "Gem": "devtools",
  "Loop": "devtools",
  "Klaviyo": "devtools",

  // ── Fintech ─────────────────────────────────────────────────
  "Stripe": "fintech",
  "Ramp": "fintech",
  "Brex": "fintech",
  "Plaid": "fintech",
  "Coinbase": "fintech",
  "Robinhood": "fintech",
  "Wealthfront": "fintech",
  "Affirm": "fintech",
  "Block": "fintech",
  "Square": "fintech",
  "Chime": "fintech",
  "Rippling": "fintech",
  "Zip": "fintech",
  "Parafin": "fintech",
  "Kikoff": "fintech",
  "Kalshi": "fintech",
  "Valon": "fintech",
  "Cedar": "fintech",
  "Bloomberg": "fintech",
  "Bloomberg LP": "fintech",
  "Capital One": "fintech",
  "BlackRock": "fintech",
  "Goldman Sachs": "fintech",
  "JPMorganChase": "fintech",
  "AppLovin": "fintech",
  "Circle": "fintech",
  "Addepar": "fintech",
  "Basis": "fintech",

  // ── Trading ─────────────────────────────────────────────────
  "Jane Street": "trading",
  "Citadel": "trading",
  "Citadel Securities": "trading",
  "Hudson River Trading": "trading",
  "Two Sigma": "trading",
  "Optiver": "trading",
  "Five Rings": "trading",
  "IMC Trading": "trading",
  "Jump Trading Group": "trading",
  "Jump Trading": "trading",
  "DRW": "trading",
  "Radix Trading LLC": "trading",
  "The Voleon Group": "trading",
  "Millennium": "trading",
  "Point72": "trading",
  "Susquehanna International Group": "trading",

  // ── Robotics ────────────────────────────────────────────────
  "Tesla": "robotics",
  "Waymo": "robotics",
  "Cruise": "robotics",
  "Zoox": "robotics",
  "Aurora": "robotics",
  "Nuro": "robotics",
  "WeRide": "robotics",
  "Rivian": "robotics",
  "Applied Intuition": "robotics",
  "Waabi": "robotics",
  "Viam": "robotics",
  "Gecko Robotics": "robotics",

  // ── Defense ─────────────────────────────────────────────────
  "SpaceX": "defense",
  "Anduril": "defense",
  "Anduril Industries": "defense",
  "Blue Origin": "defense",
  "Neuralink": "defense",
  "MIT Lincoln Laboratory": "defense",

  // ── Research labs ───────────────────────────────────────────
  "SAIL": "research-lab",
  "Stanford Artificial Intelligence Laboratory (SAIL)": "research-lab",
  "Arc Institute": "research-lab",
  "Berkeley Artificial Intelligence Research": "research-lab",
  "CSAIL": "research-lab",
  "MIT Computer Science and Artificial Intelligence Laboratory (CSAIL)": "research-lab",
  "Stanford Institute for Human-Centered Artificial Intelligence (HAI)": "research-lab",

  // ── Universities ────────────────────────────────────────────
  "Massachusetts Institute of Technology": "university",
  "Princeton University": "university",
  "Stanford University": "university",
  "Yale University": "university",
  "University of Pennsylvania": "university",
  "Columbia University": "university",
  "Duke University": "university",
  "Harvard University": "university",
  "Brown University": "university",
  "Georgia Institute of Technology": "university",
  "The University of Texas at Austin": "university",
  "MIT EECS": "university",
  "UC Berkeley Electrical Engineering & Computer Sciences (EECS)": "university",
  "Stanford University Department of Computer Science": "university",
  "Stanford University School of Engineering": "university",

  // ── Consumer / marketplaces ─────────────────────────────────
  "Uber": "consumer",
  "Airbnb": "consumer",
  "DoorDash": "consumer",
  "Lyft": "consumer",
  "Discord": "consumer",
  "Reddit, Inc.": "consumer",
  "Roblox": "consumer",
  "Pinterest": "consumer",
  "Strava": "consumer",
  "Whatnot": "consumer",
  "Patreon": "consumer",
  "Duolingo": "consumer",
  "Handshake": "consumer",
  "IXL Learning": "consumer",
  "Epic": "consumer",
  "Nourish": "consumer",

  // ── Health tech ─────────────────────────────────────────────
  "Genesis Therapeutics": "healthtech",
  "Benchling": "healthtech",
  "Brain Co.": "healthtech",

  // ── Additions — remaining top 300 ───────────────────────────
  // AI startups
  "Modal": "ai-startup",
  "Persona": "ai-startup",
  "Exa": "ai-startup",
  "Pylon": "ai-startup",
  "Parallel Web Systems": "ai-startup",
  "Sigma": "ai-startup",
  "Everlaw": "ai-startup",
  "Arena": "ai-startup",
  "micro1": "ai-startup",
  "Paraform": "ai-startup",
  "Nuvo": "ai-startup",

  // Data / infra
  "Verkada": "data-infra",
  "Samsara": "data-infra",
  "Delve": "data-infra",

  // Devtools
  "Asana": "devtools",
  "Twilio": "devtools",
  "Segment": "devtools",
  "PlanetScale": "devtools",
  "Linear": "devtools",

  // Big tech
  "Zendesk": "big-tech",
  "Palo Alto Networks (Cortex)": "big-tech",

  // Fintech
  "Shopify": "fintech",
  "PayPal": "fintech",
  "SoFi": "fintech",
  "Public": "fintech",

  // Consumer
  "Bumble": "consumer",
  "Etsy": "consumer",
  "eBay": "consumer",
  "Instacart": "consumer",
  "Grubhub": "consumer",

  // Trading
  "Balyasny Asset Management": "trading",
  "D. E. Shaw & Co": "trading",
  "Balyasny": "trading",

  // Robotics
  "Boston Dynamics": "robotics",
  "Skydio": "robotics",
  "Argo AI": "robotics",

  // Defense
  "Shield AI": "defense",
  "Lockheed Martin": "defense",
  "Raytheon": "defense",

  // Universities (common ones sourcers frequently see)
  "Carnegie Mellon University": "university",
  "University of California, Berkeley": "university",
  "UC Berkeley": "university",
  "University of Washington": "university",
  "University of Illinois Urbana-Champaign": "university",
  "Cornell University": "university",
  "California Institute of Technology": "university",
  "University of Michigan": "university",
  "New York University": "university",
  "University of Chicago": "university",
  "IIT Bombay": "university",
  "IIT Delhi": "university",
  "IIT Madras": "university",
  "KAIST": "university",
  "Tsinghua University": "university",
  "Peking University": "university",
  "University of Toronto": "university",
  "Waterloo": "university",
  "University of Waterloo": "university",
  "Cambridge University": "university",
  "University of Cambridge": "university",
  "University of Oxford": "university",

  // Research labs
  "Meta AI": "research-lab",
  "FAIR": "research-lab",
  "Microsoft Research": "research-lab",
  "Google Research": "research-lab",
  "Google X": "research-lab",
  "Allen Institute for AI": "research-lab",

  // Foundation labs
  "AI21 Labs": "foundation-lab",
  "AI21": "foundation-lab",

  // Healthtech
  "Insitro": "healthtech",
  "Recursion": "healthtech",
  "Isomorphic Labs": "healthtech",
  "PathAI": "healthtech",
  "Tempus": "healthtech",
  "Freenome": "healthtech",

  // Explicit "other" for data-quality artifacts + stealth/VC entries
  "Stealth": "other",
  "Stealth Startup": "other",
  "Stealth AI Startup": "other",
  "Software Engineer": "other",
  "Sutter Hill Ventures": "other",
  "Kleiner Perkins": "other",
  "Sequoia Capital": "other",
  "a16z": "other",
  "Andreessen Horowitz": "other",
  "South Park Commons": "other",
  "Monaco": "other",
  "Cape": "other",
  "Moment": "other",
  "Armadin": "other",
  "Percepta": "other",
  "Conversion": "other",
  "-": "other",
};
