// Auto-categorized list of Neo's PortCo companies to bulk-add as "targeting".
// Maintained as a static file so the bulk-add endpoint is reproducible
// without depending on an LLM call at runtime.
//
// Each entry will be inserted with status: "targeting", domain: "neos-portco".
// The `subdomain` field below is informational — it captures the industry
// classification I used so we can revisit if needed.

import type { EntryType } from "./types";

export interface PortcoSeed {
  name: string;
  type: EntryType;
  /** Industry classification for reference (not stored as the entry's domain) */
  subdomain: string;
  /** Optional context */
  note?: string;
}

export const NEOS_PORTCO_SEED: PortcoSeed[] = [
  // === Originally-new 125 ===
  { name: "Chai Discovery", type: "company", subdomain: "bio-ai", note: "Drug discovery / protein modeling" },
  { name: "Applied Compute", type: "company", subdomain: "frontier-ai" },
  { name: "Collaborative Robotics", type: "company", subdomain: "other", note: "Cobots / industrial robotics" },
  { name: "Bluesky", type: "company", subdomain: "vertical-saas", note: "Decentralized social network" },
  { name: "Tutor Intelligence", type: "company", subdomain: "frontier-ai" },
  { name: "Speak", type: "company", subdomain: "frontier-ai", note: "AI language learning" },
  { name: "Arrived", type: "company", subdomain: "fintech", note: "Fractional real estate investing" },
  { name: "Flint", type: "company", subdomain: "frontier-ai" },
  { name: "TextQL", type: "company", subdomain: "infra-devtools", note: "AI data analyst" },
  { name: "Yuzu", type: "company", subdomain: "other" },
  { name: "Altara", type: "company", subdomain: "other" },
  { name: "Optica Industries", type: "company", subdomain: "defense", note: "Optical / aerospace systems" },
  { name: "TELO Trucks", type: "company", subdomain: "other", note: "Compact electric trucks" },
  { name: "Astro Mechanica", type: "company", subdomain: "defense", note: "Hypersonic aerospace" },
  { name: "Valid", type: "company", subdomain: "other" },
  { name: "Sway", type: "company", subdomain: "other" },
  { name: "Adaption", type: "company", subdomain: "other" },
  { name: "Remark", type: "company", subdomain: "frontier-ai" },
  { name: "vibecode", type: "company", subdomain: "infra-devtools", note: "AI coding tool" },
  { name: "Aethero", type: "company", subdomain: "defense", note: "Space radiation / aerospace" },
  { name: "Casa", type: "company", subdomain: "fintech", note: "Bitcoin self-custody" },
  { name: "Substrate", type: "company", subdomain: "frontier-ai" },
  { name: "Deel", type: "company", subdomain: "vertical-saas", note: "Global payroll / HR" },
  { name: "Homebound", type: "company", subdomain: "vertical-saas", note: "Construction tech" },
  { name: "Collective", type: "company", subdomain: "vertical-saas" },
  { name: "Empower", type: "company", subdomain: "fintech" },
  { name: "Descript", type: "company", subdomain: "vertical-saas", note: "Video / audio editing" },
  { name: "Topos Bio", type: "company", subdomain: "bio-ai" },
  { name: "Remora", type: "company", subdomain: "other", note: "Carbon capture for trucks" },
  { name: "Engram", type: "company", subdomain: "frontier-ai" },
  { name: "Mithril", type: "company", subdomain: "other" },
  { name: "Comulate", type: "company", subdomain: "insurtech", note: "Insurance accounting" },
  { name: "Filed.", type: "company", subdomain: "vertical-saas" },
  { name: "Social Physics Lab", type: "community", subdomain: "research-lab" },
  { name: "Mecka", type: "company", subdomain: "other" },
  { name: "Frec", type: "company", subdomain: "fintech", note: "Direct indexing" },
  { name: "Relay.app", type: "company", subdomain: "infra-devtools", note: "Workflow automation" },
  { name: "Flyby Robotics", type: "company", subdomain: "other", note: "Drone delivery" },
  { name: "Axo Neurotech", type: "company", subdomain: "healthcare-ai", note: "Neurotech" },
  { name: "Serve Robotics", type: "company", subdomain: "other", note: "Sidewalk delivery robots" },
  { name: "Cassidy", type: "company", subdomain: "frontier-ai" },
  { name: "DoorList", type: "company", subdomain: "vertical-saas" },
  { name: "Amperos", type: "company", subdomain: "other" },
  { name: "Transfyr", type: "company", subdomain: "vertical-saas" },
  { name: "Dryft", type: "company", subdomain: "other" },
  { name: "Aeolus", type: "company", subdomain: "other" },
  { name: "Unconventional Inc", type: "company", subdomain: "other" },
  { name: "Detail", type: "company", subdomain: "vertical-saas" },
  { name: "PamirAI", type: "company", subdomain: "frontier-ai" },
  { name: "Actinide", type: "company", subdomain: "other", note: "Possibly nuclear / energy" },
  { name: "Roadway", type: "company", subdomain: "other" },
  { name: "Northlight", type: "company", subdomain: "other" },
  { name: "Ohana", type: "company", subdomain: "vertical-saas" },
  { name: "Ethena", type: "company", subdomain: "fintech", note: "Crypto / DeFi" },
  { name: "Gavel", type: "company", subdomain: "vertical-saas", note: "Legal tech" },
  { name: "Anterior", type: "company", subdomain: "healthcare-ai" },
  { name: "Makora", type: "company", subdomain: "other" },
  { name: "Aragon", type: "company", subdomain: "frontier-ai", note: "AI headshots" },
  { name: "Oleve", type: "company", subdomain: "frontier-ai", note: "AI study tools" },
  { name: "Manara", type: "company", subdomain: "vertical-saas", note: "MENA tech talent platform" },
  { name: "Orum", type: "company", subdomain: "vertical-saas", note: "Sales dialer" },
  { name: "GitStart", type: "company", subdomain: "infra-devtools" },
  { name: "SketchPro.ai", type: "company", subdomain: "frontier-ai", note: "AI for architecture" },
  { name: "Spoak", type: "company", subdomain: "vertical-saas" },
  { name: "ChargeUp.ai", type: "company", subdomain: "other" },
  { name: "Espa Labs", type: "company", subdomain: "frontier-ai" },
  { name: "SFOX", type: "company", subdomain: "fintech", note: "Crypto trading" },
  { name: "Pavilion", type: "company", subdomain: "vertical-saas", note: "GTM community / CRO platform" },
  { name: "Wayo", type: "company", subdomain: "other" },
  { name: "Skiff", type: "company", subdomain: "vertical-saas", note: "E2EE productivity, acquired by Notion" },
  { name: "Womp", type: "company", subdomain: "vertical-saas", note: "3D modeling" },
  { name: "Treater", type: "company", subdomain: "healthcare-ai" },
  { name: "Mage", type: "company", subdomain: "infra-devtools", note: "ML pipelines" },
  { name: "Hero Assistant (MagicX)", type: "company", subdomain: "frontier-ai" },
  { name: "Mando", type: "company", subdomain: "other" },
  { name: "OneUptime", type: "company", subdomain: "infra-devtools", note: "Open-source observability" },
  { name: "Pegasi", type: "company", subdomain: "frontier-ai" },
  { name: "Ditto", type: "company", subdomain: "infra-devtools", note: "Edge sync database" },
  { name: "Miravoice", type: "company", subdomain: "frontier-ai", note: "Voice AI" },
  { name: "Teem", type: "company", subdomain: "vertical-saas" },
  { name: "Fliteworks", type: "company", subdomain: "defense" },
  { name: "Dandy", type: "company", subdomain: "vertical-saas", note: "Dental tech" },
  { name: "Forethought", type: "company", subdomain: "frontier-ai", note: "AI customer support" },
  { name: "Castle", type: "company", subdomain: "vertical-saas" },
  { name: "folk", type: "company", subdomain: "vertical-saas", note: "CRM" },
  { name: "Swantide", type: "company", subdomain: "vertical-saas", note: "Salesforce ops automation" },
  { name: "Outgo", type: "company", subdomain: "vertical-saas" },
  { name: "Goodcall", type: "company", subdomain: "frontier-ai", note: "Voice AI for SMBs" },
  { name: "KabCash", type: "company", subdomain: "fintech" },
  { name: "Phenix Space", type: "company", subdomain: "defense", note: "Space / aerospace" },
  { name: "Intently", type: "company", subdomain: "vertical-saas" },
  { name: "Koi", type: "company", subdomain: "other" },
  { name: "Lumera Energy", type: "company", subdomain: "other", note: "Clean energy" },
  { name: "Bloom Tech", type: "company", subdomain: "vertical-saas", note: "Education / bootcamps" },
  { name: "Expedock", type: "company", subdomain: "vertical-saas", note: "Freight forwarding ops" },
  { name: "Pahdo Labs", type: "company", subdomain: "frontier-ai", note: "AI gaming" },
  { name: "Anecdote", type: "company", subdomain: "frontier-ai", note: "Customer feedback AI" },
  { name: "Proactive AI Lab Inc", type: "company", subdomain: "frontier-ai" },
  { name: "Memyard", type: "company", subdomain: "other" },
  { name: "Matey", type: "company", subdomain: "other" },
  { name: "Diddo", type: "company", subdomain: "vertical-saas" },
  { name: "Scorecard AI", type: "company", subdomain: "frontier-ai", note: "LLM eval platform" },
  { name: "brd BOT", type: "company", subdomain: "other" },
  { name: "Momento", type: "company", subdomain: "infra-devtools", note: "Serverless cache" },
  { name: "Fimio", type: "company", subdomain: "fintech" },
  { name: "Bubbl", type: "company", subdomain: "other" },
  { name: "Intros AI", type: "company", subdomain: "frontier-ai" },
  { name: "Rue", type: "company", subdomain: "vertical-saas" },
  { name: "Pelican", type: "company", subdomain: "other" },
  { name: "Circleback", type: "company", subdomain: "frontier-ai", note: "AI meeting notes" },
  { name: "Upgrade AI", type: "company", subdomain: "frontier-ai" },
  { name: "Lumaa", type: "company", subdomain: "frontier-ai" },
  { name: "Carebrain", type: "company", subdomain: "healthcare-ai" },
  { name: "Autostep", type: "company", subdomain: "other" },
  { name: "1PL", type: "company", subdomain: "vertical-saas" },
  { name: "FoodX", type: "company", subdomain: "vertical-saas" },
  { name: "Gleam", type: "company", subdomain: "vertical-saas" },
  { name: "CivCore", type: "company", subdomain: "other" },
  { name: "Crater", type: "company", subdomain: "other" },
  { name: "moss", type: "company", subdomain: "fintech", note: "Spend management" },
  { name: "principia", type: "company", subdomain: "other" },
  { name: "TIROS", type: "company", subdomain: "other" },
  { name: "Mind & Match", type: "company", subdomain: "vertical-saas" },
  { name: "Ceevra", type: "company", subdomain: "healthcare-ai", note: "3D surgical planning" },
  { name: "ScoutAI", type: "company", subdomain: "frontier-ai" },
  { name: "Beacon", type: "company", subdomain: "other" },

  // === 13 re-adds (Convex, Modal, Warp skipped — already in tracker) ===
  { name: "Kalshi", type: "company", subdomain: "fintech", note: "Event-contract exchange" },
  { name: "Moment", type: "company", subdomain: "fintech", note: "Fixed income trading" },
  { name: "Medra", type: "company", subdomain: "healthcare-ai" },
  { name: "Listen Labs", type: "company", subdomain: "frontier-ai", note: "AI user research" },
  { name: "Unify AI", type: "company", subdomain: "frontier-ai", note: "Account-based marketing AI" },
  { name: "Aven", type: "company", subdomain: "fintech", note: "HELOC card" },
  { name: "Footprint", type: "company", subdomain: "fintech", note: "KYC / identity" },
  { name: "Augment", type: "company", subdomain: "frontier-ai" },
  { name: "Caldera", type: "company", subdomain: "infra-devtools", note: "Rollups" },
  { name: "Pillar", type: "company", subdomain: "frontier-ai" },
  { name: "Gather Legacy", type: "company", subdomain: "vertical-saas" },
  { name: "Spur", type: "company", subdomain: "infra-devtools", note: "QA testing AI" },
  { name: "Dagster Labs", type: "company", subdomain: "infra-devtools", note: "Data orchestration" },
];
