// New companies to bulk-add via the apply-backfill endpoint.
// All are added with status: "new", auto-categorized by domain.
// Re-categorize in the UI after if anything looks off.

import type { Entry, EntryType, Domain } from "./types";

interface SeedItem {
  name: string;
  type: EntryType;
  domain: Domain;
  notes?: string;
}

export const BULK_ADD_ENTRIES: SeedItem[] = [
  // Originally-new 125
  { name: "Chai Discovery", type: "company", domain: "bio-ai", notes: "Drug discovery / protein modeling" },
  { name: "Applied Compute", type: "company", domain: "frontier-ai" },
  { name: "Collaborative Robotics", type: "company", domain: "other", notes: "Cobots / industrial robotics" },
  { name: "Bluesky", type: "company", domain: "vertical-saas", notes: "Decentralized social network" },
  { name: "Tutor Intelligence", type: "company", domain: "frontier-ai" },
  { name: "Speak", type: "company", domain: "frontier-ai", notes: "AI language learning" },
  { name: "Arrived", type: "company", domain: "fintech", notes: "Fractional real estate" },
  { name: "Flint", type: "company", domain: "frontier-ai" },
  { name: "TextQL", type: "company", domain: "infra-devtools", notes: "AI data analyst" },
  { name: "Yuzu", type: "company", domain: "other" },
  { name: "Altara", type: "company", domain: "other" },
  { name: "Optica Industries", type: "company", domain: "defense", notes: "Optical / aerospace" },
  { name: "TELO Trucks", type: "company", domain: "other", notes: "Compact electric trucks" },
  { name: "Astro Mechanica", type: "company", domain: "defense", notes: "Hypersonic aerospace" },
  { name: "Valid", type: "company", domain: "other" },
  { name: "Sway", type: "company", domain: "other" },
  { name: "Adaption", type: "company", domain: "other" },
  { name: "Remark", type: "company", domain: "frontier-ai" },
  { name: "vibecode", type: "company", domain: "infra-devtools", notes: "AI coding" },
  { name: "Aethero", type: "company", domain: "defense", notes: "Space radiation / aerospace" },
  { name: "Casa", type: "company", domain: "fintech", notes: "Bitcoin custody" },
  { name: "Substrate", type: "company", domain: "frontier-ai" },
  { name: "Deel", type: "company", domain: "vertical-saas", notes: "Global payroll / HR" },
  { name: "Homebound", type: "company", domain: "vertical-saas", notes: "Construction tech" },
  { name: "Collective", type: "company", domain: "vertical-saas" },
  { name: "Empower", type: "company", domain: "fintech" },
  { name: "Descript", type: "company", domain: "vertical-saas", notes: "Audio / video editing" },
  { name: "Topos Bio", type: "company", domain: "bio-ai" },
  { name: "Remora", type: "company", domain: "other", notes: "Carbon capture for trucks" },
  { name: "Engram", type: "company", domain: "frontier-ai" },
  { name: "Mithril", type: "company", domain: "other" },
  { name: "Comulate", type: "company", domain: "insurtech" },
  { name: "Filed", type: "company", domain: "vertical-saas" },
  { name: "Social Physics Lab", type: "community", domain: "research-lab" },
  { name: "Mecka", type: "company", domain: "other" },
  { name: "Frec", type: "company", domain: "fintech", notes: "Direct indexing" },
  { name: "Relay.app", type: "company", domain: "infra-devtools", notes: "Workflow automation" },
  { name: "Flyby Robotics", type: "company", domain: "other", notes: "Drone delivery" },
  { name: "Axo Neurotech", type: "company", domain: "healthcare-ai", notes: "Neurotech / medical devices" },
  { name: "Serve Robotics", type: "company", domain: "other", notes: "Sidewalk delivery robots" },
  { name: "Cassidy", type: "company", domain: "frontier-ai" },
  { name: "DoorList", type: "company", domain: "vertical-saas" },
  { name: "Amperos", type: "company", domain: "other" },
  { name: "Transfyr", type: "company", domain: "vertical-saas" },
  { name: "Dryft", type: "company", domain: "other" },
  { name: "Aeolus", type: "company", domain: "other" },
  { name: "Unconventional Inc", type: "company", domain: "other" },
  { name: "Detail", type: "company", domain: "vertical-saas" },
  { name: "PamirAI", type: "company", domain: "frontier-ai" },
  { name: "Actinide", type: "company", domain: "other" },
  { name: "Roadway", type: "company", domain: "other" },
  { name: "Northlight", type: "company", domain: "other" },
  { name: "Ohana", type: "company", domain: "vertical-saas" },
  { name: "Ethena", type: "company", domain: "fintech", notes: "Crypto / DeFi" },
  { name: "Gavel", type: "company", domain: "vertical-saas", notes: "Legal tech" },
  { name: "Anterior", type: "company", domain: "healthcare-ai" },
  { name: "Makora", type: "company", domain: "other" },
  { name: "Aragon", type: "company", domain: "frontier-ai", notes: "AI headshots" },
  { name: "Oleve", type: "company", domain: "frontier-ai", notes: "AI tutoring / study" },
  { name: "Manara", type: "company", domain: "vertical-saas", notes: "MENA tech talent platform" },
  { name: "Orum", type: "company", domain: "vertical-saas", notes: "Sales dialer" },
  { name: "GitStart", type: "company", domain: "infra-devtools" },
  { name: "SketchPro.ai", type: "company", domain: "frontier-ai", notes: "AI for architecture" },
  { name: "Spoak", type: "company", domain: "vertical-saas" },
  { name: "ChargeUp.ai", type: "company", domain: "other" },
  { name: "Espa Labs", type: "company", domain: "frontier-ai" },
  { name: "SFOX", type: "company", domain: "fintech", notes: "Crypto trading" },
  { name: "Wayo", type: "company", domain: "other" },
  { name: "Skiff", type: "company", domain: "vertical-saas", notes: "E2E encrypted productivity (acq by Notion)" },
  { name: "Womp", type: "company", domain: "vertical-saas", notes: "3D modeling" },
  { name: "Treater", type: "company", domain: "healthcare-ai" },
  { name: "Mage", type: "company", domain: "infra-devtools", notes: "ML pipelines" },
  { name: "Hero Assistant (MagicX)", type: "company", domain: "frontier-ai" },
  { name: "Mando", type: "company", domain: "other" },
  { name: "OneUptime", type: "company", domain: "infra-devtools", notes: "Open-source observability" },
  { name: "Pegasi", type: "company", domain: "frontier-ai" },
  { name: "Ditto", type: "company", domain: "infra-devtools", notes: "Edge sync database" },
  { name: "Miravoice", type: "company", domain: "frontier-ai", notes: "Voice AI" },
  { name: "Teem", type: "company", domain: "vertical-saas" },
  { name: "Fliteworks", type: "company", domain: "defense" },
  { name: "Dandy", type: "company", domain: "vertical-saas", notes: "Dental tech" },
  { name: "Forethought", type: "company", domain: "frontier-ai", notes: "AI customer support" },
  { name: "Castle", type: "company", domain: "vertical-saas" },
  { name: "folk", type: "company", domain: "vertical-saas", notes: "CRM" },
  { name: "Swantide", type: "company", domain: "vertical-saas", notes: "Salesforce automation" },
  { name: "Outgo", type: "company", domain: "vertical-saas" },
  { name: "Goodcall", type: "company", domain: "frontier-ai", notes: "Voice AI for SMBs" },
  { name: "KabCash", type: "company", domain: "fintech" },
  { name: "Phenix Space", type: "company", domain: "defense", notes: "Space / aerospace" },
  { name: "Intently", type: "company", domain: "vertical-saas" },
  { name: "Koi", type: "company", domain: "other" },
  { name: "Lumera Energy", type: "company", domain: "other", notes: "Clean energy" },
  { name: "Bloom Tech", type: "company", domain: "vertical-saas", notes: "Education / bootcamps" },
  { name: "Expedock", type: "company", domain: "vertical-saas", notes: "Logistics / freight" },
  { name: "Pahdo Labs", type: "company", domain: "other", notes: "Anime gaming" },
  { name: "Anecdote", type: "company", domain: "frontier-ai" },
  { name: "Proactive AI Lab Inc", type: "company", domain: "frontier-ai" },
  { name: "Memyard", type: "company", domain: "other" },
  { name: "Matey", type: "company", domain: "other" },
  { name: "Diddo", type: "company", domain: "frontier-ai" },
  { name: "Scorecard AI", type: "company", domain: "frontier-ai", notes: "LLM evals" },
  { name: "brd BOT", type: "company", domain: "frontier-ai" },
  { name: "Momento", type: "company", domain: "infra-devtools", notes: "Serverless cache" },
  { name: "Fimio", type: "company", domain: "fintech" },
  { name: "Bubbl", type: "company", domain: "other" },
  { name: "Intros AI", type: "company", domain: "frontier-ai" },
  { name: "Rue", type: "company", domain: "other" },
  { name: "Pelican", type: "company", domain: "other" },
  { name: "Circleback", type: "company", domain: "frontier-ai", notes: "AI meeting notes" },
  { name: "Upgrade AI", type: "company", domain: "frontier-ai" },
  { name: "Lumaa", type: "company", domain: "other" },
  { name: "Carebrain", type: "company", domain: "healthcare-ai" },
  { name: "Autostep", type: "company", domain: "other" },
  { name: "1PL", type: "company", domain: "vertical-saas" },
  { name: "FoodX", type: "company", domain: "vertical-saas" },
  { name: "Gleam", type: "company", domain: "vertical-saas" },
  { name: "CivCore", type: "company", domain: "other" },
  { name: "Crater", type: "company", domain: "other" },
  { name: "moss", type: "company", domain: "other" },
  { name: "principia", type: "company", domain: "other" },
  { name: "TIROS", type: "company", domain: "other" },
  { name: "Mind & Match", type: "company", domain: "other" },
  { name: "Ceevra", type: "company", domain: "healthcare-ai" },
  { name: "ScoutAI", type: "company", domain: "frontier-ai" },
  { name: "Beacon", type: "company", domain: "other" },

  // 13 re-adds (Convex, Modal, Warp skipped per Diego's call — already in tracker)
  { name: "Kalshi", type: "company", domain: "fintech", notes: "Prediction markets" },
  { name: "Moment", type: "company", domain: "fintech" },
  { name: "Medra", type: "company", domain: "healthcare-ai" },
  { name: "Listen Labs", type: "company", domain: "frontier-ai" },
  { name: "Unify AI", type: "company", domain: "frontier-ai" },
  { name: "Aven", type: "company", domain: "fintech" },
  { name: "Footprint", type: "company", domain: "infra-devtools", notes: "Identity verification" },
  { name: "Augment", type: "company", domain: "infra-devtools", notes: "AI coding" },
  { name: "Caldera", type: "company", domain: "infra-devtools", notes: "Crypto rollups" },
  { name: "Pillar", type: "company", domain: "vertical-saas" },
  { name: "Gather Legacy", type: "company", domain: "vertical-saas" },
  { name: "Spur", type: "company", domain: "frontier-ai", notes: "QA / testing AI" },
  { name: "Dagster Labs", type: "company", domain: "infra-devtools", notes: "Data orchestration" },
  { name: "Pavilion", type: "company", domain: "vertical-saas", notes: "GTM community" },
];

export const BULK_ADD_VERSION = "v1-2026-04-27";
