// Sequoia portfolio batch — net-new entries to add as targeting (May 1 2026)
// Health/bio, defense, insurtech, "other" domain, acquired/defunct, mega-public companies all filtered out.
// Each entry includes "(Sequoia)" suffix.

import type { EntryType, Domain } from "./types";

export interface NextBatchSeed {
  finalName: string;
  renameFrom?: string;
  type: EntryType;
  domain: Domain;
  note?: string;
}

export const SEQUOIA_BATCH_2026_05_01: NextBatchSeed[] = [
  { finalName: "Agency (Sequoia)", type: "company", domain: "frontier-ai" },
  { finalName: "Airtop (Sequoia)", type: "company", domain: "infra-devtools" },
  { finalName: "Alkira (Sequoia)", type: "company", domain: "infra-devtools" },
  { finalName: "Amplitude (Sequoia)", type: "company", domain: "vertical-saas" },
  { finalName: "Anrok (Sequoia)", type: "company", domain: "fintech" },
  { finalName: "Apex (Sequoia)", type: "company", domain: "infra-devtools" },
  { finalName: "Apollo (Sequoia)", type: "company", domain: "fintech" },
  { finalName: "Arcwise (Sequoia)", type: "company", domain: "infra-devtools" },
  { finalName: "Armis (Sequoia)", type: "company", domain: "infra-devtools" },
  { finalName: "ARQ (Sequoia)", type: "company", domain: "fintech" },
  { finalName: "Aspora (Sequoia)", type: "company", domain: "fintech" },
  { finalName: "Bigeye (Sequoia)", type: "company", domain: "infra-devtools" },
  { finalName: "Breeze.cash (Sequoia)", type: "company", domain: "fintech" },
  { finalName: "Bruce (Sequoia)", type: "company", domain: "frontier-ai" },
  { finalName: "CaptivateIQ (Sequoia)", type: "company", domain: "vertical-saas" },
  { finalName: "Catch (Sequoia)", type: "company", domain: "fintech" },
  { finalName: "Chainguard (Sequoia)", type: "company", domain: "infra-devtools" },
  { finalName: "Chkk (Sequoia)", type: "company", domain: "infra-devtools" },
  { finalName: "Citizen (Sequoia)", type: "company", domain: "vertical-saas" },
  { finalName: "Claim (Sequoia)", type: "company", domain: "vertical-saas" },
  { finalName: "Clari (Sequoia)", type: "company", domain: "vertical-saas" },
  { finalName: "Cobot (Sequoia)", type: "company", domain: "frontier-ai" },
  { finalName: "Commons (Sequoia)", type: "company", domain: "vertical-saas" },
  { finalName: "Cove (Sequoia)", type: "company", domain: "vertical-saas" },
  { finalName: "Cribl (Sequoia)", type: "company", domain: "infra-devtools" },
  { finalName: "CUE Labs (Sequoia)", type: "company", domain: "infra-devtools" },
  { finalName: "Cyera (Sequoia)", type: "company", domain: "infra-devtools" },
  { finalName: "Dashlane (Sequoia)", type: "company", domain: "infra-devtools" },
  { finalName: "Day.ai (Sequoia)", type: "company", domain: "frontier-ai" },
  { finalName: "dbt Labs (Sequoia)", type: "company", domain: "infra-devtools" },
  { finalName: "Delphi (Sequoia)", type: "company", domain: "frontier-ai" },
  { finalName: "Deno (Sequoia)", type: "company", domain: "infra-devtools" },
  { finalName: "Domino Data Lab (Sequoia)", type: "company", domain: "infra-devtools" },
  { finalName: "Doppler (Sequoia)", type: "company", domain: "infra-devtools" },
  { finalName: "Dust (Sequoia)", type: "company", domain: "frontier-ai" },
  { finalName: "Edra (Sequoia)", type: "company", domain: "frontier-ai" },
  { finalName: "EDX Markets (Sequoia)", type: "company", domain: "fintech" },
  { finalName: "Elevate (Sequoia)", type: "company", domain: "vertical-saas" },
  { finalName: "Elyn (Sequoia)", type: "company", domain: "vertical-saas" },
  { finalName: "Enter (Sequoia)", type: "company", domain: "vertical-saas" },
  { finalName: "Eon (Sequoia)", type: "company", domain: "infra-devtools" },
  { finalName: "Espresso Systems (Sequoia)", type: "company", domain: "fintech" },
  { finalName: "Ethos (Sequoia)", type: "company", domain: "fintech" },
  { finalName: "Evervault (Sequoia)", type: "company", domain: "infra-devtools" },
  { finalName: "Evy (Sequoia)", type: "company", domain: "vertical-saas" },
  { finalName: "Faraway (Sequoia)", type: "company", domain: "vertical-saas" },
  { finalName: "FastAPI Labs (Sequoia)", type: "company", domain: "infra-devtools" },
  { finalName: "Filecoin (Sequoia)", type: "company", domain: "fintech" },
  { finalName: "Fin (Sequoia)", type: "company", domain: "fintech" },
  { finalName: "Finch (Sequoia)", type: "company", domain: "fintech" },
  { finalName: "Fintual (Sequoia)", type: "company", domain: "fintech" },
  { finalName: "Fireblocks (Sequoia)", type: "company", domain: "fintech" },
  { finalName: "Firetiger (Sequoia)", type: "company", domain: "infra-devtools" },
  { finalName: "Flow Engineering (Sequoia)", type: "company", domain: "infra-devtools" },
  { finalName: "Front (Sequoia)", type: "company", domain: "vertical-saas" },
  { finalName: "Gadget (Sequoia)", type: "company", domain: "infra-devtools" },
  { finalName: "Gigi (Sequoia)", type: "company", domain: "vertical-saas" },
  { finalName: "Gladia (Sequoia)", type: "company", domain: "infra-devtools" },
  { finalName: "Gong (Sequoia)", type: "company", domain: "vertical-saas" },
  { finalName: "Grafana (Sequoia)", type: "company", domain: "infra-devtools" },
  { finalName: "Graphiant (Sequoia)", type: "company", domain: "infra-devtools" },
  { finalName: "Hallway (Sequoia)", type: "company", domain: "vertical-saas" },
  { finalName: "Ineffable Intelligence (Sequoia)", type: "company", domain: "frontier-ai" },
  { finalName: "Inferact (Sequoia)", type: "company", domain: "infra-devtools" },
  { finalName: "Infracost (Sequoia)", type: "company", domain: "infra-devtools" },
  { finalName: "Inside (Sequoia)", type: "company", domain: "vertical-saas" },
  { finalName: "Iris Labs (Sequoia)", type: "company", domain: "vertical-saas" },
  { finalName: "Iron Fish (Sequoia)", type: "company", domain: "infra-devtools" },
  { finalName: "Irregular (Sequoia)", type: "company", domain: "infra-devtools" },
  { finalName: "Island (Sequoia)", type: "company", domain: "infra-devtools" },
  { finalName: "JITX (Sequoia)", type: "company", domain: "infra-devtools" },
  { finalName: "Jive Software (Sequoia)", type: "company", domain: "infra-devtools" },
  { finalName: "Keen Technologies (Sequoia)", type: "company", domain: "frontier-ai" },
  { finalName: "Knowde (Sequoia)", type: "company", domain: "vertical-saas" },
  { finalName: "Kumo (Sequoia)", type: "company", domain: "vertical-saas" },
  { finalName: "Landis (Sequoia)", type: "company", domain: "vertical-saas" },
  { finalName: "LayerZero (Sequoia)", type: "company", domain: "fintech" },
  { finalName: "Ledgy (Sequoia)", type: "company", domain: "fintech" },
  { finalName: "Lemni (Sequoia)", type: "company", domain: "frontier-ai" },
  { finalName: "Lilt (Sequoia)", type: "company", domain: "frontier-ai" },
  { finalName: "LiquidMetal AI (Sequoia)", type: "company", domain: "infra-devtools" },
  { finalName: "Lugg (Sequoia)", type: "company", domain: "vertical-saas" },
  { finalName: "Magentic (Sequoia)", type: "company", domain: "frontier-ai" },
  { finalName: "Magic Eden (Sequoia)", type: "company", domain: "fintech" },
  { finalName: "Meeno (Sequoia)", type: "company", domain: "frontier-ai" },
  { finalName: "Meter (Sequoia)", type: "company", domain: "infra-devtools" },
  { finalName: "Monad (Sequoia)", type: "company", domain: "infra-devtools" },
  { finalName: "Mutiny (Sequoia)", type: "company", domain: "frontier-ai" },
  { finalName: "n8n (Sequoia)", type: "company", domain: "infra-devtools" },
  { finalName: "Nevis (Sequoia)", type: "company", domain: "fintech" },
  { finalName: "Noom (Sequoia)", type: "company", domain: "vertical-saas" },
  { finalName: "nsave (Sequoia)", type: "company", domain: "fintech" },
  { finalName: "Oasis Security (Sequoia)", type: "company", domain: "infra-devtools" },
  { finalName: "Observable (Sequoia)", type: "company", domain: "infra-devtools" },
  { finalName: "Omnicell (Sequoia)", type: "company", domain: "vertical-saas" },
  { finalName: "Open (Sequoia)", type: "company", domain: "vertical-saas" },
  { finalName: "Oso (Sequoia)", type: "company", domain: "infra-devtools" },
  { finalName: "Otter (Sequoia)", type: "company", domain: "vertical-saas" },
  { finalName: "Otto Finance (Sequoia)", type: "company", domain: "fintech" },
  { finalName: "Paid (Sequoia)", type: "company", domain: "vertical-saas" },
  { finalName: "Papaya (Sequoia)", type: "company", domain: "vertical-saas" },
  { finalName: "Parallel (Sequoia)", type: "company", domain: "fintech" },
  { finalName: "Parallel Web Systems (Sequoia)", type: "company", domain: "infra-devtools" },
  { finalName: "Phantom (Sequoia)", type: "company", domain: "fintech" },
  { finalName: "Piazza (Sequoia)", type: "company", domain: "vertical-saas" },
  { finalName: "Pilot (Sequoia)", type: "company", domain: "fintech" },
  { finalName: "Pocket Gems (Sequoia)", type: "company", domain: "vertical-saas" },
  { finalName: "Popsink (Sequoia)", type: "company", domain: "vertical-saas" },
  { finalName: "Prelude (Sequoia)", type: "company", domain: "infra-devtools" },
  { finalName: "Productboard (Sequoia)", type: "company", domain: "vertical-saas" },
  { finalName: "Protégé (Sequoia)", type: "company", domain: "vertical-saas" },
  { finalName: "Pydantic (Sequoia)", type: "company", domain: "infra-devtools" },
  { finalName: "QueryPal (Sequoia)", type: "company", domain: "frontier-ai" },
  { finalName: "Quilt (Sequoia)", type: "company", domain: "frontier-ai" },
  { finalName: "Rec Room (Sequoia)", type: "company", domain: "vertical-saas" },
  { finalName: "Release (Sequoia)", type: "company", domain: "infra-devtools" },
  { finalName: "Remote (Sequoia)", type: "company", domain: "vertical-saas" },
  { finalName: "RevMap (Sequoia)", type: "company", domain: "vertical-saas" },
  { finalName: "Ricursive Intelligence (Sequoia)", type: "company", domain: "frontier-ai" },
  { finalName: "Rift (Sequoia)", type: "company", domain: "vertical-saas" },
  { finalName: "Rillet (Sequoia)", type: "company", domain: "fintech" },
  { finalName: "Ruckus Networks (Sequoia)", type: "company", domain: "infra-devtools" },
  { finalName: "Safara (Sequoia)", type: "company", domain: "vertical-saas" },
  { finalName: "Safe Superintelligence (Sequoia)", type: "company", domain: "frontier-ai" },
  { finalName: "Salt Security (Sequoia)", type: "company", domain: "infra-devtools" },
  { finalName: "Sandstone (Sequoia)", type: "company", domain: "frontier-ai" },
  { finalName: "Scanner (Sequoia)", type: "company", domain: "infra-devtools" },
  { finalName: "Security Scorecard (Sequoia)", type: "company", domain: "infra-devtools" },
  { finalName: "Sesame AI (Sequoia)", type: "company", domain: "frontier-ai" },
  { finalName: "Skyramp (Sequoia)", type: "company", domain: "infra-devtools" },
  { finalName: "Snapdocs (Sequoia)", type: "company", domain: "vertical-saas" },
  { finalName: "Squint (Sequoia)", type: "company", domain: "vertical-saas" },
  { finalName: "Stainless (Sequoia)", type: "company", domain: "infra-devtools" },
  { finalName: "Stairwell (Sequoia)", type: "company", domain: "infra-devtools" },
  { finalName: "Standard Intelligence (Sequoia)", type: "company", domain: "frontier-ai" },
  { finalName: "StarkWare (Sequoia)", type: "company", domain: "fintech" },
  { finalName: "strongDM (Sequoia)", type: "company", domain: "infra-devtools" },
  { finalName: "Studeo (Sequoia)", type: "company", domain: "vertical-saas" },
  { finalName: "Sunday (Sequoia)", type: "company", domain: "vertical-saas" },
  { finalName: "Sunflower Labs (Sequoia)", type: "company", domain: "vertical-saas" },
  { finalName: "Supernova (Sequoia)", type: "company", domain: "vertical-saas" },
  { finalName: "SureIn (Sequoia)", type: "company", domain: "vertical-saas" },
  { finalName: "Synativ (Sequoia)", type: "company", domain: "vertical-saas" },
  { finalName: "Tacto (Sequoia)", type: "company", domain: "vertical-saas" },
  { finalName: "Tavus (Sequoia)", type: "company", domain: "frontier-ai" },
  { finalName: "Telda (Sequoia)", type: "company", domain: "fintech" },
  { finalName: "Telescope (Sequoia)", type: "company", domain: "frontier-ai" },
  { finalName: "The Melt (Sequoia)", type: "company", domain: "vertical-saas" },
  { finalName: "The Org (Sequoia)", type: "company", domain: "vertical-saas" },
  { finalName: "Tilt (Sequoia)", type: "company", domain: "vertical-saas" },
  { finalName: "Titus (Sequoia)", type: "company", domain: "vertical-saas" },
  { finalName: "Tourlane (Sequoia)", type: "company", domain: "vertical-saas" },
  { finalName: "Trade Republic (Sequoia)", type: "company", domain: "fintech" },
  { finalName: "Truework (Sequoia)", type: "company", domain: "fintech" },
  { finalName: "Twain (Sequoia)", type: "company", domain: "frontier-ai" },
  { finalName: "Two (Sequoia)", type: "company", domain: "fintech" },
  { finalName: "Upway (Sequoia)", type: "company", domain: "vertical-saas" },
  { finalName: "VEED (Sequoia)", type: "company", domain: "vertical-saas" },
  { finalName: "Versa Networks (Sequoia)", type: "company", domain: "infra-devtools" },
  { finalName: "Vise (Sequoia)", type: "company", domain: "fintech" },
  { finalName: "Visual Electric (Sequoia)", type: "company", domain: "frontier-ai" },
  { finalName: "WireScreen (Sequoia)", type: "company", domain: "vertical-saas" },
  { finalName: "Wonolo (Sequoia)", type: "company", domain: "vertical-saas" },
  { finalName: "XBOW (Sequoia)", type: "company", domain: "infra-devtools" },
  { finalName: "xentral (Sequoia)", type: "company", domain: "vertical-saas" },
  { finalName: "Zafran (Sequoia)", type: "company", domain: "infra-devtools" },
  { finalName: "Zapier (Sequoia)", type: "company", domain: "infra-devtools" },
  { finalName: "Zappos (Sequoia)", type: "company", domain: "vertical-saas" },
  { finalName: "Zed (Sequoia)", type: "company", domain: "infra-devtools" },
  { finalName: "Zefir (Sequoia)", type: "company", domain: "fintech" },
  { finalName: "Zum (Sequoia)", type: "company", domain: "vertical-saas" },
];
