// Thrive + Index portfolio batches — net-new entries to add as low-priority targeting (May 6 2026)
// Health/bio, defense, mega-public, acquired/defunct, NFT-gaming-crypto, lifestyle/consumer all filtered out.
// Names follow "Company Name (VC)" convention.
// All entries get priority="low" so they render in the Secondary targets tier.

import type { EntryType, Domain } from "./types";

export interface ThriveIndexSeed {
  finalName: string;
  type: EntryType;
  domain: Domain;
  source: "thrive" | "index";
}

export const THRIVE_BATCH_2026_05_06: ThriveIndexSeed[] = [
  { finalName: "Airbyte (Thrive)", type: "company", domain: "infra-devtools", source: "thrive" },
  { finalName: "Base Power Company (Thrive)", type: "company", domain: "other", source: "thrive" },
  { finalName: "Check Technologies (Thrive)", type: "company", domain: "fintech", source: "thrive" },
  { finalName: "Clair (Thrive)", type: "company", domain: "fintech", source: "thrive" },
  { finalName: "Collectors (Thrive)", type: "company", domain: "vertical-saas", source: "thrive" },
  { finalName: "Console (Thrive)", type: "company", domain: "frontier-ai", source: "thrive" },
  { finalName: "Formal (Thrive)", type: "company", domain: "infra-devtools", source: "thrive" },
  { finalName: "Guru (Thrive)", type: "company", domain: "frontier-ai", source: "thrive" },
  { finalName: "Imprint (Thrive)", type: "company", domain: "fintech", source: "thrive" },
  { finalName: "Lightspark (Thrive)", type: "company", domain: "fintech", source: "thrive" },
  { finalName: "Melio (Thrive)", type: "company", domain: "fintech", source: "thrive" },
  { finalName: "Monzo (Thrive)", type: "company", domain: "fintech", source: "thrive" },
  { finalName: "Morty (Thrive)", type: "company", domain: "fintech", source: "thrive" },
  { finalName: "Parabola (Thrive)", type: "company", domain: "infra-devtools", source: "thrive" },
  { finalName: "Pleo (Thrive)", type: "company", domain: "fintech", source: "thrive" },
  { finalName: "Revel (Thrive)", type: "company", domain: "infra-devtools", source: "thrive" },
  { finalName: "Savvy (Thrive)", type: "company", domain: "fintech", source: "thrive" },
  { finalName: "Tempo (Thrive)", type: "company", domain: "fintech", source: "thrive" },
  { finalName: "The Browser Company (Thrive)", type: "company", domain: "frontier-ai", source: "thrive" },
];

export const INDEX_BATCH_2026_05_06: ThriveIndexSeed[] = [
  { finalName: "7AI (Index)", type: "company", domain: "frontier-ai", source: "index" },
  { finalName: "Adaptive ML (Index)", type: "company", domain: "frontier-ai", source: "index" },
  { finalName: "Adfin (Index)", type: "company", domain: "infra-devtools", source: "index" },
  { finalName: "Adzuna (Index)", type: "company", domain: "vertical-saas", source: "index" },
  { finalName: "Alan (Index)", type: "company", domain: "vertical-saas", source: "index" },
  { finalName: "Albert (Index)", type: "company", domain: "vertical-saas", source: "index" },
  { finalName: "Alkemics (Index)", type: "company", domain: "vertical-saas", source: "index" },
  { finalName: "ankar.ai (Index)", type: "company", domain: "frontier-ai", source: "index" },
  { finalName: "Ankorstore (Index)", type: "company", domain: "vertical-saas", source: "index" },
  { finalName: "Apron (Index)", type: "company", domain: "fintech", source: "index" },
  { finalName: "ArthurAI (Index)", type: "company", domain: "frontier-ai", source: "index" },
  { finalName: "Ascend (Index)", type: "company", domain: "vertical-saas", source: "index" },
  { finalName: "Astelia (Index)", type: "company", domain: "vertical-saas", source: "index" },
  { finalName: "Atlantic Money (Index)", type: "company", domain: "fintech", source: "index" },
  { finalName: "Atlar (Index)", type: "company", domain: "fintech", source: "index" },
  { finalName: "AttackIQ (Index)", type: "company", domain: "infra-devtools", source: "index" },
  { finalName: "Auxmoney (Index)", type: "company", domain: "fintech", source: "index" },
  { finalName: "Beamery (Index)", type: "company", domain: "vertical-saas", source: "index" },
  { finalName: "Because (Index)", type: "company", domain: "vertical-saas", source: "index" },
  { finalName: "Behavox (Index)", type: "company", domain: "vertical-saas", source: "index" },
  { finalName: "BrightGo (Index)", type: "company", domain: "vertical-saas", source: "index" },
  { finalName: "BrightHire (Index)", type: "company", domain: "vertical-saas", source: "index" },
  { finalName: "Built (Index)", type: "company", domain: "vertical-saas", source: "index" },
  { finalName: "cargo.one (Index)", type: "company", domain: "vertical-saas", source: "index" },
  { finalName: "Codat (Index)", type: "company", domain: "fintech", source: "index" },
  { finalName: "ComplyAdvantage (Index)", type: "company", domain: "fintech", source: "index" },
  { finalName: "Covariant.ai (Index)", type: "company", domain: "vertical-saas", source: "index" },
  { finalName: "Creative Juice (Index)", type: "company", domain: "vertical-saas", source: "index" },
  { finalName: "Credit Benchmark (Index)", type: "company", domain: "fintech", source: "index" },
  { finalName: "Crossing Minds (Index)", type: "company", domain: "vertical-saas", source: "index" },
  { finalName: "Culture Amp (Index)", type: "company", domain: "vertical-saas", source: "index" },
  { finalName: "Cutover (Index)", type: "company", domain: "infra-devtools", source: "index" },
  { finalName: "DataSnipper (Index)", type: "company", domain: "infra-devtools", source: "index" },
  { finalName: "Daydream (Index)", type: "company", domain: "frontier-ai", source: "index" },
  { finalName: "Deepnote (Index)", type: "company", domain: "infra-devtools", source: "index" },
  { finalName: "/dev/agents (Index)", type: "company", domain: "frontier-ai", source: "index" },
  { finalName: "Dot Product (Index)", type: "company", domain: "frontier-ai", source: "index" },
  { finalName: "Double (Index)", type: "company", domain: "vertical-saas", source: "index" },
  { finalName: "DraftWise (Index)", type: "company", domain: "frontier-ai", source: "index" },
  { finalName: "Duffel (Index)", type: "company", domain: "vertical-saas", source: "index" },
  { finalName: "Duna (Index)", type: "company", domain: "fintech", source: "index" },
  { finalName: "Elementl (Index)", type: "company", domain: "infra-devtools", source: "index" },
  { finalName: "EthonAI (Index)", type: "company", domain: "frontier-ai", source: "index" },
  { finalName: "Expel (Index)", type: "company", domain: "infra-devtools", source: "index" },
  { finalName: "Feathery (Index)", type: "company", domain: "infra-devtools", source: "index" },
  { finalName: "Flapping Airplanes (Index)", type: "company", domain: "vertical-saas", source: "index" },
  { finalName: "flatfair (Index)", type: "company", domain: "vertical-saas", source: "index" },
  { finalName: "Fonoa (Index)", type: "company", domain: "vertical-saas", source: "index" },
  { finalName: "GeoPhy (Index)", type: "company", domain: "vertical-saas", source: "index" },
  { finalName: "Greg (Index)", type: "company", domain: "frontier-ai", source: "index" },
  { finalName: "Gremlin (Index)", type: "company", domain: "infra-devtools", source: "index" },
  { finalName: "Gruppo MutuiOnline (Index)", type: "company", domain: "fintech", source: "index" },
  { finalName: "Hoop (Index)", type: "company", domain: "vertical-saas", source: "index" },
  { finalName: "Hyperline (Index)", type: "company", domain: "infra-devtools", source: "index" },
  { finalName: "Ideogram AI (Index)", type: "company", domain: "frontier-ai", source: "index" },
  { finalName: "incident.io (Index)", type: "company", domain: "infra-devtools", source: "index" },
  { finalName: "Jumbo (Index)", type: "company", domain: "vertical-saas", source: "index" },
  { finalName: "Jump (Index)", type: "company", domain: "vertical-saas", source: "index" },
  { finalName: "Lightning AI (Index)", type: "company", domain: "frontier-ai", source: "index" },
  { finalName: "Linx Security (Index)", type: "company", domain: "infra-devtools", source: "index" },
  { finalName: "Lithic (Index)", type: "company", domain: "fintech", source: "index" },
  { finalName: "LiveKit (Index)", type: "company", domain: "infra-devtools", source: "index" },
  { finalName: "Loctax (Index)", type: "company", domain: "vertical-saas", source: "index" },
  { finalName: "Matera (Index)", type: "company", domain: "vertical-saas", source: "index" },
  { finalName: "Mercantile (Index)", type: "company", domain: "fintech", source: "index" },
  { finalName: "Mirelo (Index)", type: "company", domain: "frontier-ai", source: "index" },
  { finalName: "Monograph (Index)", type: "company", domain: "vertical-saas", source: "index" },
  { finalName: "Montonio (Index)", type: "company", domain: "fintech", source: "index" },
  { finalName: "Motive (Index)", type: "company", domain: "vertical-saas", source: "index" },
  { finalName: "Nacelle (Index)", type: "company", domain: "infra-devtools", source: "index" },
  { finalName: "Natoma (Index)", type: "company", domain: "infra-devtools", source: "index" },
  { finalName: "nexos.ai (Index)", type: "company", domain: "frontier-ai", source: "index" },
  { finalName: "Nexthink (Index)", type: "company", domain: "infra-devtools", source: "index" },
  { finalName: "Nova Credit (Index)", type: "company", domain: "fintech", source: "index" },
  { finalName: "Novus (Index)", type: "company", domain: "vertical-saas", source: "index" },
  { finalName: "Okendo (Index)", type: "company", domain: "vertical-saas", source: "index" },
  { finalName: "Otterize (Index)", type: "company", domain: "infra-devtools", source: "index" },
  { finalName: "Phaidra (Index)", type: "company", domain: "frontier-ai", source: "index" },
  { finalName: "Pitch (Index)", type: "company", domain: "vertical-saas", source: "index" },
  { finalName: "PointFive (Index)", type: "company", domain: "infra-devtools", source: "index" },
  { finalName: "Prodigy Finance (Index)", type: "company", domain: "fintech", source: "index" },
  { finalName: "Raisin (Index)", type: "company", domain: "fintech", source: "index" },
  { finalName: "ReadySet (Index)", type: "company", domain: "infra-devtools", source: "index" },
  { finalName: "Resistant AI (Index)", type: "company", domain: "infra-devtools", source: "index" },
  { finalName: "RevenueCat (Index)", type: "company", domain: "infra-devtools", source: "index" },
  { finalName: "Ryft (Index)", type: "company", domain: "vertical-saas", source: "index" },
  { finalName: "SafetyCulture (Index)", type: "company", domain: "vertical-saas", source: "index" },
  { finalName: "Sanlo (Index)", type: "company", domain: "fintech", source: "index" },
  { finalName: "Science Exchange (Index)", type: "company", domain: "vertical-saas", source: "index" },
  { finalName: "Scoop (Index)", type: "company", domain: "vertical-saas", source: "index" },
  { finalName: "Seedcamp (Index)", type: "company", domain: "vertical-saas", source: "index" },
  { finalName: "SeedLegals (Index)", type: "company", domain: "vertical-saas", source: "index" },
  { finalName: "Seso (Index)", type: "company", domain: "vertical-saas", source: "index" },
  { finalName: "Shopmonkey (Index)", type: "company", domain: "vertical-saas", source: "index" },
  { finalName: "Silverfin (Index)", type: "company", domain: "fintech", source: "index" },
  { finalName: "Siro (Index)", type: "company", domain: "vertical-saas", source: "index" },
  { finalName: "Solvo (Index)", type: "company", domain: "vertical-saas", source: "index" },
  { finalName: "Sourceful (Index)", type: "company", domain: "vertical-saas", source: "index" },
  { finalName: "Spendesk (Index)", type: "company", domain: "fintech", source: "index" },
  { finalName: "Spiko (Index)", type: "company", domain: "fintech", source: "index" },
  { finalName: "Strapi (Index)", type: "company", domain: "infra-devtools", source: "index" },
  { finalName: "Sublime Security (Index)", type: "company", domain: "infra-devtools", source: "index" },
  { finalName: "Subset (Index)", type: "company", domain: "vertical-saas", source: "index" },
  { finalName: "Superconductive (Index)", type: "company", domain: "infra-devtools", source: "index" },
  { finalName: "Superlinked (Index)", type: "company", domain: "infra-devtools", source: "index" },
  { finalName: "Sylvera (Index)", type: "company", domain: "vertical-saas", source: "index" },
  { finalName: "Taktile (Index)", type: "company", domain: "fintech", source: "index" },
  { finalName: "Taxfix (Index)", type: "company", domain: "fintech", source: "index" },
  { finalName: "Tebi (Index)", type: "company", domain: "fintech", source: "index" },
  { finalName: "tessl.io (Index)", type: "company", domain: "frontier-ai", source: "index" },
  { finalName: "Thatch (Index)", type: "company", domain: "vertical-saas", source: "index" },
  { finalName: "Toolbx (Index)", type: "company", domain: "vertical-saas", source: "index" },
  { finalName: "Transcend (Index)", type: "company", domain: "infra-devtools", source: "index" },
  { finalName: "Upollo (Index)", type: "company", domain: "vertical-saas", source: "index" },
  { finalName: "Valdera (Index)", type: "company", domain: "vertical-saas", source: "index" },
  { finalName: "Venice (Index)", type: "company", domain: "vertical-saas", source: "index" },
  { finalName: "Vinyl Equity (Index)", type: "company", domain: "fintech", source: "index" },
  { finalName: "Vizcom (Index)", type: "company", domain: "frontier-ai", source: "index" },
  { finalName: "Vooma (Index)", type: "company", domain: "vertical-saas", source: "index" },
  { finalName: "Vouch (Index)", type: "company", domain: "fintech", source: "index" },
  { finalName: "Wonderful (Index)", type: "company", domain: "vertical-saas", source: "index" },
  { finalName: "Wordsmith (Index)", type: "company", domain: "frontier-ai", source: "index" },
  { finalName: "Workbounce (Index)", type: "company", domain: "vertical-saas", source: "index" },
  { finalName: "Worldover (Index)", type: "company", domain: "vertical-saas", source: "index" },
  { finalName: "Xata (Index)", type: "company", domain: "infra-devtools", source: "index" },
  { finalName: "Mistral (Index)", type: "company", domain: "frontier-ai", source: "index" },
];
