import type { Entry } from "./types";

// Status conventions for seed:
// - "tried" = on the original tags list (heavily mined already)
// - "targeting" = on the curated list user wanted to check
// - "new" = surfaced as suggestions but not yet acted on

let id = 0;
const e = (
  name: string,
  status: Entry["status"],
  type: Entry["type"],
  domain: Entry["domain"],
  notes?: string
): Entry => ({
  id: `seed-${++id}`,
  name,
  status,
  type,
  domain,
  notes,
  addedAt: Date.now(),
});

export const SEED_ENTRIES: Entry[] = [
  // === TARGETING (the cleaned list) ===
  e("Black Forest Labs", "targeting", "company", "frontier-ai"),
  e("Runway", "targeting", "company", "frontier-ai"),
  e("Ideogram", "targeting", "company", "frontier-ai"),
  e("Suno", "targeting", "company", "frontier-ai"),
  e("Liquid AI", "targeting", "company", "frontier-ai"),
  e("World Labs", "targeting", "company", "frontier-ai"),
  e("Reka AI", "targeting", "company", "frontier-ai"),
  e("Magic", "targeting", "company", "frontier-ai"),

  e("PathAI", "targeting", "company", "healthcare-ai"),
  e("Paige.AI", "targeting", "company", "healthcare-ai"),
  e("Hippocratic AI", "targeting", "company", "healthcare-ai"),
  e("Abridge", "targeting", "company", "healthcare-ai"),
  e("Ambience Healthcare", "targeting", "company", "healthcare-ai"),
  e("OpenEvidence", "targeting", "company", "healthcare-ai"),
  e("Suki AI", "targeting", "company", "healthcare-ai"),
  e("Color Health", "targeting", "company", "healthcare-ai"),
  e("Verily", "targeting", "company", "healthcare-ai"),
  e("Recursion Pharmaceuticals", "targeting", "company", "bio-ai"),
  e("Insitro", "targeting", "company", "bio-ai"),
  e("Profluent", "targeting", "company", "bio-ai"),
  e("Genesis Therapeutics", "targeting", "company", "bio-ai"),
  e("Nuance Communications", "targeting", "company", "healthcare-ai"),
  e("Nabla", "targeting", "company", "healthcare-ai"),
  e("Heidi Health", "targeting", "company", "healthcare-ai"),
  e("Akasa", "targeting", "company", "healthcare-ai"),

  e("Lemonade", "targeting", "company", "insurtech"),
  e("Hippo", "targeting", "company", "insurtech"),

  e("SpaceX", "targeting", "company", "defense"),
  e("Anduril", "targeting", "company", "defense"),
  e("Saronic Technologies", "targeting", "company", "defense"),
  e("Skydio", "targeting", "company", "defense"),
  e("Shield AI", "targeting", "company", "defense"),
  e("Vannevar Labs", "targeting", "company", "defense"),
  e("Rebellion Defense", "targeting", "company", "defense"),
  e("RTX", "targeting", "company", "defense"),

  e("Supabase", "targeting", "company", "infra-devtools"),
  e("Neon", "targeting", "company", "infra-devtools"),
  e("PlanetScale", "targeting", "company", "infra-devtools"),
  e("Turbopuffer", "targeting", "company", "infra-devtools"),

  // === TRIED (heavily mined per the original tag list) ===
  e("Meta", "tried", "company", "frontier-ai", "Saturated"),
  e("Palantir Technologies", "tried", "company", "vertical-saas", "Saturated"),
  e("Robinhood", "tried", "company", "fintech", "Saturated"),
  e("Citadel", "tried", "company", "fintech", "Saturated"),
  e("Glean", "tried", "company", "vertical-saas", "Heavily mined"),
  e("Anyscale", "tried", "company", "infra-devtools", "Heavily mined"),
  e("Scale AI", "tried", "company", "frontier-ai", "Heavily mined"),
  e("Figma", "tried", "company", "vertical-saas"),
  e("Rippling", "tried", "company", "vertical-saas"),
  e("Ramp", "tried", "company", "fintech"),
  e("Databricks", "tried", "company", "infra-devtools"),
  e("Anthropic", "tried", "company", "frontier-ai"),
  e("OpenAI", "tried", "company", "frontier-ai"),
  e("xAI", "tried", "company", "frontier-ai"),
  e("Google DeepMind", "tried", "company", "frontier-ai"),
  e("Mistral AI", "tried", "company", "frontier-ai"),
  e("Cohere", "tried", "company", "frontier-ai"),
  e("Together AI", "tried", "company", "frontier-ai"),
  e("Fireworks AI", "tried", "company", "frontier-ai"),
  e("Perplexity", "tried", "company", "frontier-ai"),
  e("Cursor (Anysphere)", "tried", "company", "frontier-ai"),
  e("Harvey", "tried", "company", "vertical-saas"),
  e("Decagon", "tried", "company", "vertical-saas"),
  e("Sierra", "tried", "company", "vertical-saas"),
  e("Clay", "tried", "company", "vertical-saas"),
  e("Cognition", "tried", "company", "frontier-ai"),
  e("Stripe", "tried", "company", "fintech"),
  e("Plaid", "tried", "company", "fintech"),
  e("Brex", "tried", "company", "fintech"),
  e("Notion", "tried", "company", "vertical-saas"),
  e("Retool", "tried", "company", "infra-devtools"),
  e("Vercel", "tried", "company", "infra-devtools"),
  e("Linear", "tried", "company", "infra-devtools"),
  e("Sentry", "tried", "company", "infra-devtools"),
  e("Datadog", "tried", "company", "infra-devtools"),
  e("Snowflake", "tried", "company", "infra-devtools"),
  e("MongoDB", "tried", "company", "infra-devtools"),
  e("Cloudflare", "tried", "company", "infra-devtools"),
  e("Crusoe", "tried", "company", "infra-devtools"),
  e("Mercor", "tried", "company", "vertical-saas"),
  e("Snorkel AI", "tried", "company", "frontier-ai"),
  e("SambaNova Systems", "tried", "company", "infra-devtools"),
  e("Waymo", "tried", "company", "defense"),
  e("Cruise", "tried", "company", "defense"),
  e("Aurora", "tried", "company", "defense"),
  e("Nuro", "tried", "company", "defense"),
  e("Tesla", "tried", "company", "defense"),
  e("Applied Intuition", "tried", "company", "defense"),
  e("Character.AI", "tried", "company", "frontier-ai"),
  e("Rubrik", "tried", "company", "infra-devtools"),
  e("Codeium / Windsurf", "tried", "company", "infra-devtools"),
  e("Pylon", "tried", "company", "vertical-saas"),
  e("Hightouch", "tried", "company", "infra-devtools"),
  e("Strava", "tried", "company", "vertical-saas"),
  e("Zip", "tried", "company", "vertical-saas"),
  e("Snap", "tried", "company", "vertical-saas"),
  e("Pika", "tried", "company", "frontier-ai"),
  e("ElevenLabs", "tried", "company", "frontier-ai"),
  e("Hume AI", "tried", "company", "frontier-ai"),
  e("Moveworks", "tried", "company", "vertical-saas"),

  // Schools - tried
  e("MIT", "tried", "school", "cs-school", "Heavily covered"),
  e("Stanford", "tried", "school", "cs-school", "Heavily covered"),
  e("UC Berkeley", "tried", "school", "cs-school", "Heavily covered"),
  e("CMU", "tried", "school", "cs-school", "Heavily covered"),
  e("Waterloo", "tried", "school", "cs-school"),
  e("Princeton", "tried", "school", "cs-school"),
  e("Harvard", "tried", "school", "cs-school"),
  e("Yale", "tried", "school", "cs-school"),
  e("Cornell", "tried", "school", "cs-school"),
  e("UCLA", "tried", "school", "cs-school"),
  e("UIUC", "tried", "school", "cs-school"),
  e("Columbia", "tried", "school", "cs-school"),
  e("UPenn", "tried", "school", "cs-school"),
  e("Duke", "tried", "school", "cs-school"),
  e("Brown", "tried", "school", "cs-school"),
  e("Dartmouth", "tried", "school", "cs-school"),
  e("Northwestern", "tried", "school", "cs-school"),
  e("UChicago", "tried", "school", "cs-school"),
  e("Rice", "tried", "school", "cs-school"),
  e("Johns Hopkins", "tried", "school", "cs-school"),
  e("UT Austin", "tried", "school", "cs-school"),

  // Elite HS - tried
  e("TJ", "tried", "school", "elite-hs", "Saturated"),
  e("Stuyvesant", "tried", "school", "elite-hs", "Saturated"),
  e("Harker", "tried", "school", "elite-hs", "Saturated"),
  e("IMSA", "tried", "school", "elite-hs", "Saturated"),
  e("Lynbrook", "tried", "school", "elite-hs", "Saturated"),
  e("Bronx Science", "tried", "school", "elite-hs"),

  // Competitions - tried
  e("IMO", "tried", "competition", "olympiad"),
  e("IOI", "tried", "competition", "olympiad"),
  e("Putnam", "tried", "competition", "olympiad"),
  e("ICPC", "tried", "competition", "olympiad"),
  e("AIME", "tried", "competition", "olympiad"),
  e("IPhO", "tried", "competition", "olympiad"),

  // Communities - tried
  e("YC", "tried", "community", "fellowship"),
  e("Neo", "tried", "community", "fellowship"),
  e("KP Fellows", "tried", "community", "fellowship"),
  e("Thiel Fellows", "tried", "community", "fellowship"),
  e("Forbes 50", "tried", "community", "fellowship"),

  // === NEW (suggestions surfaced earlier, not yet acted on) ===
  e("Sakana AI", "new", "company", "frontier-ai", "Tokyo only — no US office"),
  e("Helsing", "new", "company", "defense", "Munich/London/Paris"),
  e("Reflection AI", "new", "company", "frontier-ai"),
  e("Thinking Machines Lab", "new", "company", "frontier-ai"),
  e("Goodfire", "new", "company", "frontier-ai"),
  e("Physical Intelligence", "new", "company", "defense"),
  e("Skild AI", "new", "company", "defense"),
  e("1X", "new", "company", "defense"),
  e("Figure", "new", "company", "defense"),
  e("Tempus AI", "new", "company", "healthcare-ai", "Post-IPO, lockup expired"),
  e("Commure", "new", "company", "healthcare-ai"),
  e("Counsel Health", "new", "company", "healthcare-ai"),
  e("Candid Health", "new", "company", "healthcare-ai"),
  e("Cohere Health", "new", "company", "healthcare-ai"),
  e("Garner Health", "new", "company", "healthcare-ai"),
  e("Datavant", "new", "company", "healthcare-ai"),
  e("Flatiron Health", "new", "company", "healthcare-ai"),
  e("Truveta", "new", "company", "healthcare-ai"),
  e("Atomwise", "new", "company", "bio-ai"),
  e("Schrödinger", "new", "company", "bio-ai"),
  e("Generate Biomedicines", "new", "company", "bio-ai"),
  e("Inceptive", "new", "company", "bio-ai"),
  e("Cradle.bio", "new", "company", "bio-ai"),
  e("Manifold Bio", "new", "company", "bio-ai"),
  e("Arc Institute", "new", "company", "research-lab"),
  e("Broad Institute", "new", "community", "research-lab"),
  e("Mercury", "new", "company", "fintech"),
  e("Modern Treasury", "new", "company", "fintech"),
  e("Column", "new", "company", "fintech"),
  e("Increase", "new", "company", "fintech"),
  e("Pave", "new", "company", "fintech"),
  e("Watershed", "new", "company", "vertical-saas"),
  e("Persona", "new", "company", "vertical-saas"),
  e("Cockroach Labs", "new", "company", "infra-devtools"),
  e("HashiCorp", "new", "company", "infra-devtools"),
  e("Temporal", "new", "company", "infra-devtools"),
  e("Render", "new", "company", "infra-devtools"),
  e("Fly.io", "new", "company", "infra-devtools"),
  e("Convex", "new", "company", "infra-devtools"),
  e("Turso", "new", "company", "infra-devtools"),
  e("GitHub", "new", "company", "infra-devtools"),
  e("Confluent", "new", "company", "infra-devtools"),
  e("Cresta", "new", "company", "vertical-saas"),
  e("Hex", "new", "company", "vertical-saas"),
  e("Baseten", "new", "company", "infra-devtools"),
  e("Modal", "new", "company", "infra-devtools"),
  e("LangChain", "new", "company", "infra-devtools"),
  e("Chalk", "new", "company", "infra-devtools"),
  e("Mintlify", "new", "company", "infra-devtools"),
  e("Resend", "new", "company", "infra-devtools"),
  e("Liveblocks", "new", "company", "infra-devtools"),
  e("Inngest", "new", "company", "infra-devtools"),
  e("Trigger.dev", "new", "company", "infra-devtools"),

  // Insurtech - new
  e("Next Insurance", "new", "company", "insurtech"),
  e("Oscar Health", "new", "company", "insurtech"),
  e("Devoted Health", "new", "company", "insurtech"),
  e("Pie Insurance", "new", "company", "insurtech"),
  e("Hometap", "new", "company", "insurtech"),
  e("Coalition", "new", "company", "insurtech"),
  e("At-Bay", "new", "company", "insurtech"),

  // Schools - new (under-mined)
  e("Caltech", "new", "school", "cs-school"),
  e("University of Washington", "new", "school", "cs-school"),
  e("University of Michigan", "new", "school", "cs-school"),
  e("Georgia Tech", "new", "school", "cs-school"),
  e("EPFL", "new", "school", "cs-school"),
  e("ETH Zurich", "new", "school", "cs-school"),
  e("TU Munich", "new", "school", "cs-school"),
  e("Tsinghua", "new", "school", "cs-school"),
  e("Peking University", "new", "school", "cs-school"),
  e("IIT Bombay", "new", "school", "cs-school"),
  e("IIT Delhi", "new", "school", "cs-school"),
  e("IIT Madras", "new", "school", "cs-school"),
  e("Technion", "new", "school", "cs-school"),
  e("NUS", "new", "school", "cs-school"),
  e("NTU Singapore", "new", "school", "cs-school"),
  e("University of Tokyo", "new", "school", "cs-school"),
  e("KAIST", "new", "school", "cs-school"),
  e("Mila / U. Montreal", "new", "school", "cs-school"),

  // Communities - new
  e("Hertz Foundation Fellows", "new", "community", "fellowship"),
  e("Marshall Scholars", "new", "community", "fellowship"),
  e("Schmidt Futures", "new", "community", "fellowship"),
  e("Emergent Ventures", "new", "community", "fellowship"),
  e("MATS Research", "new", "community", "fellowship"),
  e("South Park Commons", "new", "community", "fellowship"),
  e("Recurse Center", "new", "community", "fellowship"),
  e("Pioneer.app", "new", "community", "fellowship"),

  // Open source - new
  e("vLLM contributors", "new", "community", "open-source"),
  e("LangChain contributors", "new", "community", "open-source"),
  e("LlamaIndex contributors", "new", "community", "open-source"),
  e("Ray / Anyscale contributors", "new", "community", "open-source"),
  e("PyTorch core contributors", "new", "community", "open-source"),
  e("HuggingFace transformers contributors", "new", "community", "open-source"),
  e("DSPy contributors", "new", "community", "open-source"),
  e("OpenAI evals contributors", "new", "community", "open-source"),

  // Competitions - new
  e("Codeforces grandmasters (non-US)", "new", "competition", "olympiad"),
  e("Kaggle Grandmasters", "new", "competition", "olympiad"),
  e("Linguistics Olympiad", "new", "competition", "olympiad"),
  e("NOI China medalists", "new", "competition", "olympiad"),
  e("ICFP Programming Contest", "new", "competition", "olympiad"),
  e("HCMUS / Vietnam-HCM team", "new", "competition", "olympiad"),
  e("iGEM (synbio)", "new", "competition", "olympiad"),
];
